apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secrets
    namespace: home-assistant
type: Opaque
stringData:
    secrets.yaml: ENC[AES256_GCM,data:NNn2GeL5Z+mcUOo/Xd6+s7KH2uRIvsPpaDmBGCszyKOmD3oveGxcFqD7u1+2EdkZ0Gh054n29Ez9G7xj5AtmTSDk3E//8VYGbZQ=,iv:BHG44NdGLywyGTENpokH1g4nxYn0G2lDkgSrqCSVzhE=,tag:fOTJ0Z72gEo4IbMhttQ1bA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWbk1QdUc4NDNhNFVuU3pY
            NUdsNHU3VjQ2MkV1bjRiWXA1WHp6Zk8vS2d3Ci80YWIwTHU5TE5jQWlzNXZsT2w5
            M2tsdXZQOC96N2JMQ252OFBuRzRLWTAKLS0tIGNxRVZpZi9KSThaK1hqaDJ2bm1O
            R1QyekcwSFRrTEVyV09EVXVNSDBTNXcK2nZiUIqBhlGq0GiRB97NfHmuvJ13lzW5
            H8nWrlmAnkc+3iMWceQPnM3wu65SohtwXzW6nNCE7EAQ4Ke4MCbS+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g4erccmqr8znqmhszfyq425l6dt9thq7vmllrn7z9yjfaug3putqlgs4ry
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-03T21:40:43Z"
    mac: ENC[AES256_GCM,data:fIWF0fb8RToNiGEETKaAGTNiO5BHEU0v6GgmjtqJOSqMLH/E1FWtDBDztKx0LbK7i0l1/ZabKnyHv+PL98EQXvX0rcwNZnYIsjPITQwtwOPXQksW6p9Xvb7ZtNViyzMw486elJsz4WqAMXqDeQkYXiOogHur4G8zILP95tMmD8s=,iv:WOq6XQCXD+Yd8ThonxsU1eev0H6a1QSYMo3oUmic140=,tag:8EPuwmak4WVbIW4kdPiWsg==,type:str]
    version: 3.13.0
