---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      version: "2.10.2"
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: kube-system
  # https://github.com/grafana/helm-charts/blob/main/charts/loki-stack/values.yaml
  # https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml
  values:
    promtail:
      enabled: true
      extraPorts:
        syslog:
          name: tcp-syslog
          containerPort: 1514
          service:
            port: 80
            type: LoadBalancer
            externalTrafficPolicy: Local
            loadBalancerIP: 192.168.3.241
      config:
        snippets:
          extraScrapeConfigs: |
            # Add an additional scrape config for syslog
            - job_name: syslog
              syslog:
                listen_address: 0.0.0.0:{{ .Values.extraPorts.syslog.containerPort }}
                label_structured_data: yes
                labels:
                  job: syslog
              relabel_configs:
                - source_labels:
                    - __syslog_message_hostname
                  target_label: hostname

                # example label values: kernel, CRON, kubelet
                - source_labels:
                    - __syslog_message_app_name
                  target_label: app

                # example label values: debug, notice, informational, warning, error
                - source_labels:
                    - __syslog_message_severity
                  target_label: level
    loki:
      enabled: true
      isDefault: false
      serviceMonitor:
        enabled: true
        additionalLabels:
          app.kubernetes.io/part-of: kube-prometheus-stack
      config:
        chunk_store_config:
          max_look_back_period: 0s
        table_manager:
          retention_deletes_enabled: true
          retention_period: 12h
