---
apiVersion: v1
kind: Service
metadata:
  name: foundryvtt
  labels:
    name: foundryvtt
  namespace: foundryvtt
spec:
  selector:
    app: foundryvtt
  ports:
    - name: web
      port: 80
      targetPort: 30000
