---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../infra/network/gateway
  - ./synology-certificate.yaml
patches:
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: Gateway
      name: internal
      namespace: gateway
    patch: |-
      - op: add
        path: /spec/listeners/-
        value:
          protocol: HTTPS
          port: 443
          name: synology-https-gateway
          hostname: synology.petebeegle.com
          tls:
            mode: Terminate
            certificateRefs:
              - kind: Secret
                name: synology-petebeegle-com
          allowedRoutes:
            namespaces:
              from: All
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: Gateway
      name: passthrough
      namespace: gateway
    patch: |-
      - op: add
        path: /spec/listeners/-
        value:
          protocol: TLS
          port: 443
          name: pve01-passthrough
          hostname: pve01.petebeegle.com
          tls:
            mode: Passthrough
          allowedRoutes:
            namespaces:
              from: All
      - op: add
        path: /spec/listeners/-
        value:
          protocol: TLS
          port: 443
          name: pve02-passthrough
          hostname: pve02.petebeegle.com
          tls:
            mode: Passthrough
          allowedRoutes:
            namespaces:
              from: All
      - op: add
        path: /spec/listeners/-
        value:
          protocol: TLS
          port: 443
          name: pve03-passthrough
          hostname: pve03.petebeegle.com
          tls:
            mode: Passthrough
          allowedRoutes:
            namespaces:
              from: All
      - op: add
        path: /spec/listeners/-
        value:
          protocol: TLS
          port: 443
          name: pve04-passthrough
          hostname: pve04.petebeegle.com
          tls:
            mode: Passthrough
          allowedRoutes:
            namespaces:
              from: All
      - op: add
        path: /spec/listeners/-
        value:
          protocol: TLS
          port: 443
          name: unifi-passthrough
          hostname: unifi.petebeegle.com
          tls:
            mode: Passthrough
          allowedRoutes:
            namespaces:
              from: All
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: HTTPRoute
      name: https-redirect
      namespace: gateway
    patch: |-
      - op: add
        path: /spec/hostnames/-
        value: synology.petebeegle.com
