---
- name: Install MetalLB
  ansible.builtin.shell: |
    kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/{{ kubernetes_metallb_version }}/config/manifests/metallb-native.yaml
- name: Create address pool
  block:
    - name: Copy resources
      ansible.builtin.template:
        src: files/config.yml
        dest: /tmp/kubernetes_metallb_config.yml
        mode: "0644"
    - name: Create pools
      ansible.builtin.command: kubectl apply -f /tmp/kubernetes_metallb_config.yml
      register: result
      until: result.rc == 0
      retries: 5
      delay: 10
      ignore_errors: true
