---
- name: Validate kubernetes_metallb_version
  ansible.builtin.assert:
    that:
      - kubernetes_metallb_version is defined
      - kubernetes_metallb_version is string
    success_msg: kubernetes_metallb_version is valid
    fail_msg: kubernetes_metallb_version is not valid
- name: Validate kubernetes_metallb_address_pool
  ansible.builtin.assert:
    that:
      - kubernetes_metallb_address_pool is defined
      - kubernetes_metallb_address_pool is string
    success_msg: kubernetes_metallb_address_pool is valid
    fail_msg: kubernetes_metallb_address_pool is not valid
