- name: Initialize the cluster using docker swarm
  community.docker.docker_swarm:
    state: present
  register: swarm
- name: Cache join tokens
  ansible.builtin.set_fact:
    join_tokens: "{{ swarm.swarm_facts.JoinTokens }}"
    cacheable: true
- name: Create proxy network
  community.docker.docker_network:
    name: proxy
    driver: overlay
