apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-${branch_slug}-secrets
    namespace: jellyfin-${branch_slug}
type: Opaque
stringData:
    JELLYFIN_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:dUQ44BQg0GioAQb0pkbW5uyRKtikRPZHJovOBSkSZc2AanDLZxWb8XX60iRgB19MeXRfAbq6MDeIjuG0Ij8pyA==,iv:2fiofw4595fjEzGPzQYVJxk75NdUNW8yq0FUiGDAidY=,tag:er51EZdc4QQUSrBBQI8nKA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFM01aaXdORnJ1bmJ4dk5X
            MkQyL1JxSVZISVB6clNFQlJEUHJRY0tmZ0ZzCkNxRlNBU1Q1TzBpT3ZDelZjWWY1
            N2gzcmNXZDRNOWpFeVlmelNuRkFuN0EKLS0tIFVSelBMUk40YUpuRWsyR01WMmts
            MU5KWTJObU8xbndWV05zOVJVZjc3MEEKrY3d0ACJwpLS2yDtx4Sdh0aPl+i1jmXs
            tindAKztdTb6R5N28gUYrOY1zry7ucMwwO1aEwxaceulqfjPlK4I3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g4erccmqr8znqmhszfyq425l6dt9thq7vmllrn7z9yjfaug3putqlgs4ry
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T18:39:07Z"
    mac: ENC[AES256_GCM,data:Ax9xQ7tuoY01XPpK61CwVRIuvgDbaAAWfatPrjXmlcank+wPYfsBkPL2cstP/fZpz5NxdHFAG1hHDTbC5LYHQrFj4UlrjEpeLwee/Wj2khotM0GPiK5FZU4vwlxRMB14eJPJce9w0JfvrLiGbftAhghd3OWX8kfCJRK3GpMCgcE=,iv:7IFv1jxV+pEK5vyQCYWEm2OWPGtno1p9fZcen90SlZk=,tag:ochiHaFTAELwsaRybenzRg==,type:str]
    version: 3.13.0
