---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: access-broker-data
  namespace: access-broker
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-csi-storage
  resources:
    requests:
      storage: 1Gi
