apiVersion: v1
kind: Secret
metadata:
    name: access-broker-secret
    namespace: access-broker
type: Opaque
stringData:
    DISCORD_APP_ID: ENC[AES256_GCM,data:Z5Bqs44Jw+I8WQ==,iv:SBdHqQPR+n8a8zWPr0oPD3gZLRLNqSFG7spNM56dZW4=,tag:BGj3LXcIaE0lmHWkPrPXQw==,type:str]
    DISCORD_PUBLIC_KEY: ENC[AES256_GCM,data:lzBcay0j+tvp9A==,iv:bXTSy3+ZL7yi+qKJdV8niw9xc2ZtuJQK11Gzim2pbIM=,tag:nihfdGnt002ePekc53ZYmA==,type:str]
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:HE0EGpBekN+uCw==,iv:CC2Evm3s254hqavW3cL/LDlNisECJWxbCPYzED0BlIA=,tag:ZImRuWF6yrl22YX/SXjFeA==,type:str]
    AUTHENTIK_TOKEN: ENC[AES256_GCM,data:TQWlcS9j2X9Q2Q==,iv:T0onIHePCxwFJrBjEmc8GYii+hX05dP4wKxsuPDlMac=,tag:ar7auHk1JQfiBEZeTXtgIQ==,type:str]
    WGEASY_PASSWORD: ENC[AES256_GCM,data:6pweEfyCFehm7w==,iv:Cy+cOF7f+ukF4h3/mQRfg8iCI6vZzk92RjGMy2dKRXc=,tag:2t7QNk1J2qu1XMPsMtZtgQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwL3JScDIxcnArbndoU1ho
            ZlVyZHdKVS9rN0dzWWR6ZkkyWkZCMmQ5OGw0CjdaWlpZellpRUhlQ3FYSy9nOTVS
            ZmIzRWlIdkZBR2VWVS9XdEVLcXhMNkUKLS0tIHNnQm8zNmJFbTI5SGwvaW1mb3NP
            Mk5FdnVBckZ3UnRoeUJtajhaZVRoWXcK/JbAnJtKbagRZPSoT1OylkaR3avsT9ol
            Yc3g1sTZjoYf6BZVA6l4QDxJGVJF+DYtdziW5Q69rTcer+0az57Qsg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g4erccmqr8znqmhszfyq425l6dt9thq7vmllrn7z9yjfaug3putqlgs4ry
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-04T18:51:22Z"
    mac: ENC[AES256_GCM,data:CKUT58tKfcRGVh68Qnm8hp4xi9oOzriPSwkkMyBh+Qs1qGRHKFw1oBQzIGhoumBL4QwQDROgezRoseaID6X5xy5W25OVuvEg7voVUEj8qnx05/AE/JcnzEM1vhxf7zmv6wNTMaAeHdfECSEIra6H1W0/ETuuH/2DE9Q820qfqmo=,iv:r6SWR3PlhEc1u0nAcSZnOE/kbKMo5kY5LBbycnQtIn8=,tag:zmRCAF1B9pdhJAZaVJNJeA==,type:str]
    version: 3.13.0
