apiVersion: v1
kind: Secret
metadata:
    name: access-broker-secret
    namespace: access-broker
type: Opaque
stringData:
    DISCORD_APP_ID: ENC[AES256_GCM,data:DLbJDLjT3FjruMtkfuPP/bZmFw==,iv:vUZZ5PWSW8xicAVOAyhbWviV2JLi6Ro2bpznWNsnfO8=,tag:3HI5xKbCwJ2PQSzzA/b0Iw==,type:str]
    DISCORD_PUBLIC_KEY: ENC[AES256_GCM,data:GmWEKQ3MJjRba/bJwTo+pFWY9n5A8mZF5aVzziIIGiFETKlo8CX1RuzklHZfEsPnyql6XgpzcCq4CPyUiY0AeQ==,iv:+k3shLq+zuJ74gN7h8fRprGShHfhaHyyxKzJFH8u+L0=,tag:nfxEOl1wIjyVhb/REDXw/A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRk12Rm1xdTVqRzhNL3lR
            Y21EaWZ2eGRsdGJGVTYxT2twTnFDdU5IM3lnCklEemVMcDBKOUk1UU1KaEMrZWtp
            ZlRXQnhQNHNVaGtxVmd3T3dmOS85YkEKLS0tIG5ZbDEvUU9lS0ZPZ3Nsb1hPMnFH
            a3hMTFdwbFhBZVJ0TU5XVnY3N0pMQVkKP1+QyWPfQBHevW+tAt7fnwCpJeWt+xYF
            UsbWNDplzwTWkTeQOiQ7YxAB7lmNosLHIlcrON1i/ZQAcNTVIY+AlA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g4erccmqr8znqmhszfyq425l6dt9thq7vmllrn7z9yjfaug3putqlgs4ry
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-04T19:20:39Z"
    mac: ENC[AES256_GCM,data:AyVweCaTh5JYDtXN8d261q9aDBriRDIaoD8v6K+hf6FIkCjRNpA74JX66KltxKCMk47hgmOPaDxRv4UduAv3MkegB9xtwdzmSJE547QeDLIE0q6LoHWdfp0JGCwv32jKItki+LV4u/vU65YMDSexL+nj9oy6nx+rgYiF95/EL8g=,iv:80O4HcyGQ3+lwfKJkBJBRCusohkONbI1ZEhoSODYRK4=,tag:rG11BVHfDi7fjMx6UejtUQ==,type:str]
    version: 3.13.0
