apiVersion: v1
kind: Secret
metadata:
    name: access-broker-secret
    namespace: access-broker
type: Opaque
stringData:
    DISCORD_APP_ID: ENC[AES256_GCM,data:DLbJDLjT3FjruMtkfuPP/bZmFw==,iv:vUZZ5PWSW8xicAVOAyhbWviV2JLi6Ro2bpznWNsnfO8=,tag:3HI5xKbCwJ2PQSzzA/b0Iw==,type:str]
    DISCORD_PUBLIC_KEY: ENC[AES256_GCM,data:GmWEKQ3MJjRba/bJwTo+pFWY9n5A8mZF5aVzziIIGiFETKlo8CX1RuzklHZfEsPnyql6XgpzcCq4CPyUiY0AeQ==,iv:+k3shLq+zuJ74gN7h8fRprGShHfhaHyyxKzJFH8u+L0=,tag:nfxEOl1wIjyVhb/REDXw/A==,type:str]
    DISCORD_CLIENT_SECRET: ENC[AES256_GCM,data:wVbkThRfuhoNMvzFZE+9Wl16zeODszJghsltl9klhl8=,iv:INYS6j/7V5pU3OMuTLAVEOG8uTLci1swytKEaQJZkCk=,tag:qe/8u5Y1HSw/Q5PT6W/9rQ==,type:str]
    AUTHENTIK_TOKEN: ENC[AES256_GCM,data:+BEHK6w/oxjsfkY7ojwTkbOPYi2/ZuXiWEfmyS0pxEiTk3FqR6QudpXrXuc=,iv:PrET7pREvNd7WgQQ4fcaCAKgNkY5NKYtq/nXB1tIRq8=,tag:MAU3TByHV13Fnbh8j5Vj8Q==,type:str]
    WGEASY_PASSWORD: ENC[AES256_GCM,data:6TuHowHkJaKhF3GAKR/AXQ9pqw==,iv:D3Hfdc2OqaTxmUCUiDD+6o/vheujBNZoRFDBZlR6rms=,tag:jatkPQoMGvUKvW3rnAiBoA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRk12Rm1xdTVqRzhNL3lR
            Y21EaWZ2eGRsdGJGVTYxT2twTnFDdU5IM3lnCklEemVMcDBKOUk1UU1KaEMrZWtp
            ZlRXQnhQNHNVaGtxVmd3T3dmOS85YkEKLS0tIG5ZbDEvUU9lS0ZPZ3Nsb1hPMnFH
            a3hMTFdwbFhBZVJ0TU5XVnY3N0pMQVkKP1+QyWPfQBHevW+tAt7fnwCpJeWt+xYF
            UsbWNDplzwTWkTeQOiQ7YxAB7lmNosLHIlcrON1i/ZQAcNTVIY+AlA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g4erccmqr8znqmhszfyq425l6dt9thq7vmllrn7z9yjfaug3putqlgs4ry
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T00:07:32Z"
    mac: ENC[AES256_GCM,data:M7mH3j/8cgIcM15uIBAZf6CjJfRzht6IoIBqbEAvXZlFLgPFZoO6+vtPHAd0DXUOINuszYem53xD8P9t9yjyEiwsgZhZBIsmoiRfOzXXrMNjdqOCCQYPgEqQtpIW0XKDurOlXGN7JpUPGU1DR/FnkxmfQQwEYEMxpSL5ahj7AiM=,iv:8jPtQgrwP9NaxdanwfZcbNF7wDYEGx7/8zyrRLeyXRQ=,tag:sMWYpWhSaJRp2bEjss+sbg==,type:str]
    version: 3.13.0
