---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi-media-storage
  resources:
    requests:
      storage: 1Ti
