apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:7Lt+yobmx+FhkBzDfNbL2YosQxNi65i2avnQKippxltdRWWp4uP9gOSDSt5dAsug47U=,iv:ziEaoubEKmWfRmTWFlL4Ugs5R4loH1+TJmRCP5yupmg=,tag:rVaL4U7YMxAOUkf1Jaocxw==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:XqzlPilDckjhCtzkwSmHq+vdl0Wy80+fU+Szg9yA894Psft9vRfrxBStu4o=,iv:/xCvnRmqkjMmqh46eX5EW9F8SHD6rzGYl3mpAfD2J7A=,tag:a+LQpMvB94qmkErJabx7Nw==,type:str]
    password: ENC[AES256_GCM,data:jj6cBIXrlS1tnTWHBLA9LniGF8d9R8BWpBaYi95GmsBLVDAv81HOYig8EbU=,iv:3v3dFWjc/wP+DcN/07XiC2LrGWrWZBkeT6P8oq7QiGw=,tag:BLihMRNWdm/ehPDAKDy0zA==,type:str]
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:JI1J2dBpyx24FyRFTYF5FsnhDFQv,iv:U1n+nooKrY1PggOO80HdTV5RebdTg9EGConJ960LW9c=,tag:pglaP9vh0ZyeT565uzgIIQ==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:nryoVSFvHbReJ1EmYbOw2t98rYPwWEUFr5SCHHvSsZrBxXUwsb2/wDG1aq4=,iv:6HO6WsB6bHLkMkPLhKsnJIoE/lunMlcDA46BIjDIf0E=,tag:g5D5vFFt95itbeMWlmwwrg==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:eegUTnScRsxU3kKuiAutk3kJDmJ3E1O8o5ulZ+DbYyE8/q8eSnYhdgn5yn8=,iv:lURMceviYoTdvWTM6u0YRVC+PWtxaAOGSexvrudtDQA=,tag:G4a7lP1hmxajk890Jv5AeA==,type:str]
    GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:D00HusIULHupXnMU5WMutIogp78dOTOjG2bnP1VxqZoChekVXkTeCbXnTr0=,iv:iB2Vdfa+M+/OK86PNWh07wj2vxI5Oh+slMMm0VKZ1Tk=,tag:l1MoDsq5lLdgld3Wi01IPQ==,type:str]
    SYNOLOGY_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:UXGtV6opF/tc+ZBoc14tGJhTPB+myLFOi1q38UzN9gBn27ykb+md0J9pbH0=,iv:SLfhAYSkiAfdKkj09YGDqHtxaWcvZA9URxRxj+vVmWQ=,tag:j5xJYAbbJ39DJjdTsiISLw==,type:str]
    JELLYFIN_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:4t3Q2JQe+ZsAlYU684/1o3WibGitzXoFFMrXgZ3yqu7E20hfZmFZzgGs0ftB1DU4//yC+ga8RI5GrQJ4sOwvDQ==,iv:quarjdhDN2/ddxUUqaphlDls0vUszYE7Ebm6zDwAfxU=,tag:M9K8iwZ0XJ8x9v9hWIYJHg==,type:str]
    IMMICH_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:TeMKvJqLXD4bScHzrKocw6o6Oe5lV0TONyst/m7lgiojyClIguPs9FksIDjzx+GxkxjUayxNcgUBQ4tcyfUcVQ==,iv:feJxmnV8ZsU8346KEOydXj7o2jAKoIFc0dWk1pNIu68=,tag:XfGOrh9OYpPhb2c+N9Y/8g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBub0ttb0RtZmQveU5RUXpP
            YjYzWXFDYWJQaFEvSEFxaDRsS2daN2Z2R0JZCng5RDd0UzlGSis3cmtWWTdwYzlK
            Tm85UVdSMTBnUE1zYUxYWEl6WXhvd00KLS0tIEFiSHpYZ1I5clhWMmJQT0NZSDNr
            aDk0VlZWYzFXQVd1emJaYU9ZelVBV0UKU+iUuMgZgImI7VdLHPZK0XKHz0xoVbSh
            bGCk8agjIr2pYV6Vigg0qS1NhAm6mKaRn0bZ4Cy4Jbs3X/ii+iK/GQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g4erccmqr8znqmhszfyq425l6dt9thq7vmllrn7z9yjfaug3putqlgs4ry
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-04T15:29:03Z"
    mac: ENC[AES256_GCM,data:iFQgORRlMGYWMqVGRIllg/fhb7cwp1juRlFxom9pewG0ROlDOZc998W4TOt1xNLwdpoOIZU9JiP5yMy3U74tctqQcHuwHuuqz4L0mrCLaUlUG6jfMbtsYj2/KzEIKeVg3SJJ+uppVJwHTy7hCaEQnwRxZyDL/05FTZxeP9JNXXc=,iv:Op1OsMt5Xc+BxbN6EnjEPh0+fLCHGVjdCP99afPJnPo=,tag:lF+90VmaSNVy5CKdldZ+Lg==,type:str]
    version: 3.13.0
