apiVersion: v1
kind: Secret
metadata:
  name: wireguard-env
  namespace: wireguard
type: Opaque
stringData:
  WG_HOST: ENC[AES256_GCM,data:BVAkK52CsMVgwsBqJA==,iv:sU/1/4bC5c4dloasSaQf16KuRHx8wxbkHjoHyJTLKSM=,tag:xz2F7310O8o8UC2eGiQ/ag==,type:str]
  WG_PORT: ENC[AES256_GCM,data:R4yOSyQ=,iv:G8UT/Hg/eP/rWKfdsSimFc2q5Mep0IgLVh0C9FQMXD0=,tag:qqT3xsqQ058E45sPRspwgA==,type:str]
  WG_ALLOWED_IPS: ENC[AES256_GCM,data:ZulHRfOWEcEbMRnQTPNTrME5kv2aaeOUsm36qFg=,iv:3S79ZpgFp0LMoYg25L9mahpmASC2xb0wsu9Iyovxybo=,tag:tZOTzEBlERSCitb1nW7/aA==,type:str]
sops:
  age:
    - recipient: age1g4erccmqr8znqmhszfyq425l6dt9thq7vmllrn7z9yjfaug3putqlgs4ry
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSWFiTi96clVvQ045SlVw
        WnFOZVJBTzgvS3ExakJxNXRsbDNVTDJYRG5zCnlSajk1bUFpLzh1R1JicnBSNHhl
        QVVzd0JxWStqVEYycnp4Y3hQVVRzMncKLS0tIFNJaGRGYUVPQkQwdXVHY3dSMUxt
        MGozd0NUQVhHWFJLSDlrWHZxaWxSekkK9Tc0HANTdB8U5X/FgiJITz0oceQ3mX1W
        drsISfRDi0wfPNQiBlV+47znoZCwMw+EXwtioLMYS6kWZlsk88WHSw==
        -----END AGE ENCRYPTED FILE-----
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-12T02:50:57Z"
  mac: ENC[AES256_GCM,data:qca2jYsMcMiTv58c57Tb3PiGqWKFxPwZIwmrL0QX62nAZ5GCjajuh5/9f+2EX86RbKWCIDSNTgWoBJemlOvklM20idgL16t2Fzg2YmjH1M3Fy5b5+AV6S4zvl7s+QJaqHHvm2+0NKIyU15SaQpQ7CrjuLEfnVFMT/0cTYgYAwzY=,iv:92Rb4nG2GRXa02KrRt1Dmb/hOkdyJ5ZTjGCxTwuf71w=,tag:8fBsBqD1ecjYcpDczw9+HA==,type:str]
  version: 3.10.2
