apiVersion: v1
kind: Secret
metadata:
  name: wireguard-env
  namespace: wireguard
type: Opaque
stringData:
  WG_HOST: ENC[AES256_GCM,data:BVAkK52CsMVgwsBqJA==,iv:sU/1/4bC5c4dloasSaQf16KuRHx8wxbkHjoHyJTLKSM=,tag:xz2F7310O8o8UC2eGiQ/ag==,type:str]
  WG_PORT: ENC[AES256_GCM,data:R4yOSyQ=,iv:G8UT/Hg/eP/rWKfdsSimFc2q5Mep0IgLVh0C9FQMXD0=,tag:qqT3xsqQ058E45sPRspwgA==,type:str]
  WG_ALLOWED_IPS: ENC[AES256_GCM,data:b8l1mJQqDz79N4Cqxg==,iv:XFb8JO0of3BhrnX+duPl+6gT2Gc3V2srPOtI7c07F8I=,tag:lub2QM+eOCOPvXL9F3jmDA==,type:str]
sops:
  age:
    - recipient: age1g4erccmqr8znqmhszfyq425l6dt9thq7vmllrn7z9yjfaug3putqlgs4ry
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSWFiTi96clVvQ045SlVw
        WnFOZVJBTzgvS3ExakJxNXRsbDNVTDJYRG5zCnlSajk1bUFpLzh1R1JicnBSNHhl
        QVVzd0JxWStqVEYycnp4Y3hQVVRzMncKLS0tIFNJaGRGYUVPQkQwdXVHY3dSMUxt
        MGozd0NUQVhHWFJLSDlrWHZxaWxSekkK9Tc0HANTdB8U5X/FgiJITz0oceQ3mX1W
        drsISfRDi0wfPNQiBlV+47znoZCwMw+EXwtioLMYS6kWZlsk88WHSw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-22T00:51:59Z"
  mac: ENC[AES256_GCM,data:FxfieBnlsdmNZAJePBs7ICY3ZVIXgg91k91viCT4FRlzlwyYYTUDWl+CyPSFcjpcX59xTKWEQoDRCdGAxRklSI1Xy4h5dM7n/8AN3mJeX0ZJ4fJStvJWIH688pTzw40FrmlEtAmrj0O62znxtPDA0b/LnkNsYiVzZnDhQkzQXCg=,iv:7ZxTwlqrJOOWXwVI29ERtOSYP6b/txE7Vh2dCI8RTXo=,tag:AprgwV3QBQfcSMen0NW9Eg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
