apiVersion: v1
kind: Secret
metadata:
  name: wireguard-env
  namespace: wireguard
type: Opaque
stringData:
  WG_HOST: ENC[AES256_GCM,data:BVAkK52CsMVgwsBqJA==,iv:sU/1/4bC5c4dloasSaQf16KuRHx8wxbkHjoHyJTLKSM=,tag:xz2F7310O8o8UC2eGiQ/ag==,type:str]
  WG_PORT: ENC[AES256_GCM,data:R4yOSyQ=,iv:G8UT/Hg/eP/rWKfdsSimFc2q5Mep0IgLVh0C9FQMXD0=,tag:qqT3xsqQ058E45sPRspwgA==,type:str]
sops:
  age:
    - recipient: age1g4erccmqr8znqmhszfyq425l6dt9thq7vmllrn7z9yjfaug3putqlgs4ry
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSWFiTi96clVvQ045SlVw
        WnFOZVJBTzgvS3ExakJxNXRsbDNVTDJYRG5zCnlSajk1bUFpLzh1R1JicnBSNHhl
        QVVzd0JxWStqVEYycnp4Y3hQVVRzMncKLS0tIFNJaGRGYUVPQkQwdXVHY3dSMUxt
        MGozd0NUQVhHWFJLSDlrWHZxaWxSekkK9Tc0HANTdB8U5X/FgiJITz0oceQ3mX1W
        drsISfRDi0wfPNQiBlV+47znoZCwMw+EXwtioLMYS6kWZlsk88WHSw==
        -----END AGE ENCRYPTED FILE-----
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-12T04:28:54Z"
  mac: ENC[AES256_GCM,data:qh5yMwTS1Hl3m2Lev4X6ie12h1WOx/G0+asw8a6vJ5hAW3uKs4jpChrXEkVsR07NGEDt6ALzD2D8ITksN5Wwkq/Jo744lgDQ0y3kOC2/iHStz1TBKIOGKT4V48+NduGVicUNUP+iYJxlWb6urQChCk99X6amswpzQzDiJj86isU=,iv:+ExTypN0xPP8V7DmznurJC7YkoxF+wjN+wryNstXEGc=,tag:0RMbq1C2qNoGYtV+WZTeMQ==,type:str]
  version: 3.10.2
