apiVersion: v1
kind: Secret
metadata:
  name: wireguard-env
  namespace: wireguard
type: Opaque
stringData:
  WG_HOST: ENC[AES256_GCM,data:YqMifAFSS7GIeC8P6A==,iv:KjZ1nrrn1DROV0wgyyXWKLFFjW1laQyODfMbDAdgOsM=,tag:CoRi01tJ29G9BKv3/pFXbA==,type:str]
  WG_PORT: ENC[AES256_GCM,data:R4yOSyQ=,iv:G8UT/Hg/eP/rWKfdsSimFc2q5Mep0IgLVh0C9FQMXD0=,tag:qqT3xsqQ058E45sPRspwgA==,type:str]
sops:
  age:
    - recipient: age1g4erccmqr8znqmhszfyq425l6dt9thq7vmllrn7z9yjfaug3putqlgs4ry
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSWFiTi96clVvQ045SlVw
        WnFOZVJBTzgvS3ExakJxNXRsbDNVTDJYRG5zCnlSajk1bUFpLzh1R1JicnBSNHhl
        QVVzd0JxWStqVEYycnp4Y3hQVVRzMncKLS0tIFNJaGRGYUVPQkQwdXVHY3dSMUxt
        MGozd0NUQVhHWFJLSDlrWHZxaWxSekkK9Tc0HANTdB8U5X/FgiJITz0oceQ3mX1W
        drsISfRDi0wfPNQiBlV+47znoZCwMw+EXwtioLMYS6kWZlsk88WHSw==
        -----END AGE ENCRYPTED FILE-----
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-03T01:56:35Z"
  mac: ENC[AES256_GCM,data:EV6RvdeA6UMx0YmffTPvjRrV64yiqjYek1O/CUjgRLYxHkFsWHfnCBQ9FA0vIkU+wFOyh6VfjONTETrRsN/6m+HQ+a3fJiOIOSGnCdQiPgRQHMHB+qv9n1vJJdYpmAMnBrxCrzgjNbei+mkJqqfunqzkXKfzY44LIfoOwCeamUA=,iv:W3+DuwTmfNnPxmPM2JJne8NWsvTO8a1rWr0jh0babxA=,tag:8d6YJMeifV2wK1YLQOJbYw==,type:str]
  version: 3.10.2
