apiVersion: v1
kind: Secret
metadata:
    name: grafana-credentials
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:Txzfk0c=,iv:oGrBYhKXBwL4ZciEQQCdMSaLCAoTBXfquNGzw8eiCnQ=,tag:egaEcDJ+w9yZi8fyK4OGNw==,type:str]
    admin-password: ENC[AES256_GCM,data:J85EyxQHab0f8GUa9NcyZfM52yI=,iv:loefwBbB/Lk8WiNyqkYYJm7SHjWfbVglR7nYBP5/FG4=,tag:UbyvXaRK3+R91n+TviXHRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g4erccmqr8znqmhszfyq425l6dt9thq7vmllrn7z9yjfaug3putqlgs4ry
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpcmY1YWJpbzBzSXFoZVM5
            OHNuaFZjNGY3ZTdIb2ZOUE5rUXBGZksyMG1ZCjBMVzg4MEIwaTQra3JvckxBQnRL
            UTBjSXBOeFNkeG9qVEFWUzRLYndCTDQKLS0tICtHM1p5bUdkZ092U3FsWVcyZTkv
            MnlyU3FRRERSaitzblpDNU1jbWQrVHcK+sp8nHvYJrxUxGpkcf3kVqHt+rVXYnPj
            L2g0i+Cvl6o8gDl+R2UAaaJuno0u+HGdgJ7CrRQqMdefqH+zvFamTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-02T03:47:26Z"
    mac: ENC[AES256_GCM,data:3Nwvm50fS9K3owVp0N0w355A+IHS8etpdP+vE8GRDUDXwwVLfrjvpk1WDPZQcDuNOAvbAU2BKo3OgOPocpJ1u6WIhCRNzAYwQNCa/3/ujRYE+Hsb2PBFzMa2dxnP0ZxlFQP3fxl12ThWjp9xv9wmeV54fMlQLn0tCsbU0fJ82m4=,iv:adCqj3EjxJLWlx+V53GWBTTw/pYP7jgLGUOB30RyfpY=,tag:jsD5i5BxpOlF2qUQt5x3kg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
