---
- name: Include validation tasks
  ansible.builtin.import_tasks: validate.yml

- name: Download ISO
  become: true
  ansible.builtin.get_url:
    url: "{{ download_iso_download_url }}"
    dest: "{{ download_iso_out_dir }}/{{ download_iso_image_name }}"
    mode: "0664"
  register: cloud_image
- name: Set download_iso_cloud_image_dest fact
  ansible.builtin.set_fact:
    download_iso_cloud_image_dest: "{{ cloud_image.dest }}"
