# This file contains variables used across all playbooks and roles.
---
# Local configurations
local:
  # The directory where the output files will be stored
  out_dir: "{{ lookup('ansible.builtin.env', 'WORKSPACE_FOLDER') }}/.out"

# Talos-specific configurations
talos:
  # The URL to download the Talos image.
  # This url is built from the wysiwyg at https://factory.talos.dev
  download_url: https://factory.talos.dev/image/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515/v1.7.4/nocloud-amd64.iso
  # The name of the Talos image to create.
  image_name: talos-v1.7.4-nocloud-amd64.iso
  # Remote location where the image is stored
  image_src: truenas-nfs:iso/
  # Kubernetes cluster name
  cluster_name: talos-proxmox-cluster
  # Controlplane specific configurations
  control_plane:
    # Endpoint for the control plane
    endpoint: https://192.168.3.60:6443

# Kubernetes configurations
kubernetes:
  # The NFS server to use for the NFS CSI driver
  nfs_share: /mnt/pool/k8s-data
  # The version of the NFS CSI driver to use
  # see: https://github.com/kubernetes-csi/csi-driver-nfs/blob/master/README.md
  nfs_csi_version: v4.7.0
  # The version of the Calico CNI plugin to use
  calico_version: v3.28.0
  # The version of the MetalLB load balancer to use
  metallb_version: v0.14.5
  # The address pool to use for the MetalLB load balancer
  address_pool: 192.168.3.200/27 # .193-.222
  # The CIDR to use for the Calico network
  calico_cidr: 10.244.0.0/16

# Networking configurations
networking:
  # The network interface to use for the VMs
  gateway_ip: 192.168.3.1

# Proxmox-specific configurations
proxmox:
  # The connection string to the Proxmox server
  api_url: https://192.168.3.2:8006/api2/json
  # The token id to authenticate with the Proxmox server
  token_id: ansible@pam!ansible
  # The token secret to authenticate with the Proxmox server
  token_secret: "{{ proxmox_token_secret }}"

# Ssh configurations
ssh:
  # The private key to use to connect to the VMs
  proxmox_private_key: "{{ proxmox_vm_ssh_private_key }}"
