apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cloudflared
  namespace: cloudflare
  labels:
    app: cloudflared
spec:
  selector:
    matchLabels:
      app: cloudflared
  podMetricsEndpoints:
    - port: "2000"
      path: /metrics
      interval: 30s
