apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: cloudflare
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:zcwcTXKtpd7N0/9azoxBVWJAjp4xj9o5wGpnoCI5yTaHq7r5CazQ0A1Ef/pvbYHbPB64HIBBNHeW6mNQrck1GFzHqaStB6cZ/GzBi9VDl0gRNLr9LdM4eUXk/qHu/myzZ8w35YdzT1jrIwrQZ5d7oSXgiMgh17/JipheLuswrpV7cgUBU5au0w+IlZU7xqXkqOwx/1FctmcqpUWAQG8W8qs1,iv:cAua7gPqIXU7FV3cgCkFbcwtjmo94rd/nP2ZJEMjZ+Q=,tag:Zle3ZeqKNJcAATSdCjU9SQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g4erccmqr8znqmhszfyq425l6dt9thq7vmllrn7z9yjfaug3putqlgs4ry
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRUU1ak5qU3l3UzF2WVA1
            bFJNZGE1bVJQMVZqVHR1cnhscWgweWlxSnhjCk9FTzJhNkFncGl3eUZKTmJOdk85
            M2lpVzZYaFZkb3VVUzkvTUpNKzRtcGcKLS0tIEU4MkpJaVdhVk5NSnhnQWdoU051
            Y2V4Z1Z6OVNqUGExc0trY0dMNER1T3MKQoN8bLyNAcWvDRrd9dhOOxvXfjpsq0Mv
            cCDMGstf+KFLnlu+jqUDnSC2a9fbgla7IUgfbEER83mmdL2dfikUIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-21T05:30:51Z"
    mac: ENC[AES256_GCM,data:+7vKS1t/S3oiscXG7xH02S3wDx2v2enQE9B5R9QvzmZKlqkWh4d3TxTfc6eLg1l0X7kh0I8FttIkH37e9rqEYCHu3u92S4bgchRfvfaY7C1CY1g4R6ulm+d2tqXQYgRNhc5s9mUJ5fc1FWj4qfS5IU8w5Up+xbtZdzu3wXW/1i8=,iv:YxxWrWT72KE16yFQFLfg5Skor266b2zdaiEGlqUt7ns=,tag:uY3ITBW41qRRHSsOm4VJAQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
