---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../certs
patches:
  - target:
      group: cert-manager.io
      version: v1
      kind: ClusterIssuer
    patch: |-
      - op: replace
        path: /spec/acme/solvers/0/dns01/cloudflare/apiTokenSecretRef/name
        value: cloudflare-api-token-onepassword
