---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: synology-csi
  namespace: dataplane
spec:
  interval: 5m
  releaseName: synology-csi
  chart:
    spec:
      chart: synology-csi
      sourceRef:
        kind: HelmRepository
        name: synology-csi-chart
        namespace: flux-system
      version: "0.9.5-pre.1"
  values:
    clientInfoSecret:
      create: false
      name: synology-csi-secret
    storageClasses:
      synology-iscsi-storage:
        disabled: false
        isDefault: true
        reclaimPolicy: Retain
        volumeBindingMode: Immediate
        parameters:
          location: /volume2
          fsType: 'btrfs'
          dsm: 192.168.3.27
          formatOptions: '--nodiscard'
      synology-nfs-storage:
        disabled: false
        isDefault: false
        reclaimPolicy: Retain
        volumeBindingMode: Immediate
        parameters:
          protocol: nfs
          location: /volume2
          dsm: 192.168.3.27
          fsType: ext4
          mountPermissions: '0755'
          mountOptions: 'nfsvers=4.1'
    volumeSnapshotClasses:
      synology-iscsi-snapshot:
        deletionPolicy: Delete
