apiVersion: v1
kind: Secret
metadata:
    name: synology-csi-secret
    namespace: dataplane
type: Opaque
stringData:
    client-info.yml: ENC[AES256_GCM,data:Ncl1MijCkJkrRVe6k4vi2Ox9VLnRbA87aG/3Hop4W1FVxwTfqhowU5ErdGbMkO6RCmowP+U/jT4pzkquzmzxl4H/9HPDZQ7NGQTne365PUm1b3AYShB+dtcEU/4Fgiy4KnOZ3qZO5JyHs9TqxG+wxaSKuEIx/KjdtuFeKazT4BUAyqJ+iqg9gxWqplgzZkZwDj8LaTkC6dFOzcRLXTqTsvwilbrPV8QFdQFXUZRzDuSTcDPTlhKmwXr95lCmWjE1x6Pcki4dM/Qb1yTE4WveP3okqwMMIYI/WGIDtUKtgSVT0C4nnIY=,iv:ICw6iQIERfH+QwhqGMMOFwe0LDKCdWCqVs/5TSxx5v8=,tag:4mn17jQhVnxgQ2FLXmlGVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g4erccmqr8znqmhszfyq425l6dt9thq7vmllrn7z9yjfaug3putqlgs4ry
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWjROaitCUzQ2dWV5aXp2
            WEN6dXNLQmdSZWlnaDE0UjFnc0JKWmFiU1RjClN3bXo4TzBydGZhU0c4YUloSUtT
            b0NqVFMxS3k2ZUFjbnl0QzRLTTdhdjAKLS0tIFpEL1dubkxRRjVubitNT2dQTks2
            Q2ViWWlvNFhOb05qeFVhSGEwSlVtTUUK2bip+MSWSki+rsBQ9351m2kbDVC+YC49
            PKK9V5SaPU8MoQRjSeU6NeQR8qy7XhZycgBpa4gQrcRHEzFfaAG7Gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-19T04:15:05Z"
    mac: ENC[AES256_GCM,data:osunQ9gggZB1N02XzpgSTAjPCv+Ag6/CHj1zEGiMZ7SF7+r2GPghnGsdofSIaSIifJTCFvRs6btBGebWwi5oU1OIvkE56rIUQiOLQ7O5rlAEfdsmFIoRqqLCkjUYsaUG0wovQIgqlE5c+Erube0PilG+XCUC+iu6nETa1KfaV68=,iv:iIckmoPLL3lqcEab66mkGkSO/r6ISdIs0/VolW164dc=,tag:ieYGfpQaNO1UPHxxtHOtvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
