---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-lab-petebeegle-com
  namespace: gateway
spec:
  secretName: wildcard-lab-petebeegle-com
  dnsNames:
    - "*.lab.petebeegle.com"
  issuerRef:
    name: cloudflare
    kind: ClusterIssuer
