---
creation_rules:
  - path_regex: secret.yaml
    encrypted_regex: ^(data|stringData)$
    age: >-
      age1g4erccmqr8znqmhszfyq425l6dt9thq7vmllrn7z9yjfaug3putqlgs4ry
  - path_regex: grafana-env.yaml
    encrypted_regex: ^(data|stringData)$
    age: >-
      age1g4erccmqr8znqmhszfyq425l6dt9thq7vmllrn7z9yjfaug3putqlgs4ry
