---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: ip-pool
  namespace: kube-system
spec:
  blocks:
    - cidr: 192.168.30.240/28
---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: external-ip-pool
  namespace: kube-system
spec:
  blocks:
    - cidr: 192.168.40.240/28
  serviceSelector:
    matchLabels:
      homelab.petebeegle.com/exposure: external
