---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: ip-pool
  namespace: kube-system
spec:
  blocks:
    - cidr: ${gateway_internal_pool}
---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: external-ip-pool
  namespace: kube-system
spec:
  blocks:
    - cidr: ${gateway_external_pool}
  serviceSelector:
    matchLabels:
      homelab.petebeegle.com/exposure: external
