---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/bookmarks

- resources:
    - modem:
      - abbr: MO
        href: "https://modem.{{HOMEPAGE_VAR_DOMAIN}}"

- developer:
    - source:
      - abbr: GH
        href: https://github.com/petebeegle/homelab
