---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/bookmarks

- Developer:
    - Source:
        - abbr: GH
          href: https://github.com/petebeegle/homelab
