---
default_config:

homeassistant:
  unit_system: us_customary
  currency: USD
  country: US
  time_zone: America/New_York
  external_url: https://homeassistant-${branch_slug}.${cluster_domain}
  internal_url: https://homeassistant-${branch_slug}.${cluster_domain}
  auth_providers:
    - type: homeassistant
  packages: !include_dir_named packages

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.244.0.0/16

prometheus:
  namespace: homeassistant
  requires_auth: false
  filter:
    include_domains:
      - light
      - switch
      - binary_sensor
      - sensor
      - person
      - device_tracker
      - automation
      - climate
      - cover
      - fan
      - lock
      - update

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
