---
default_config:

homeassistant:
  external_url: https://homeassistant-${branch_slug}.${cluster_domain}
  internal_url: https://homeassistant-${branch_slug}.${cluster_domain}
  auth_providers:
    - type: homeassistant
  packages: !include_dir_named packages

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.244.0.0/16

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
