apiVersion: v1
kind: Secret
metadata:
    name: grafana-env
    namespace: grafana
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:Ic3qrQ3tTaiCIXhQyhRWHW4TBxKFXuVc1m+CtMVi3VvKQO+1iERu84WlzuooxbfzRHlSYVtwbhAlj8MVXKg8LZr9yhdv5Z4Jbb7Be1fQPS+UHtdvUPHFxerW53VuriIjBmSRtjYU4Yt/vVz9UVpkzIsq6B1G010IoA==,iv:zwzPQ92o8C6OfzU1prJbdL4hgjn+BLx602Nq8GrUJRs=,tag:NhiKen4eB7Gg5b2Vno6fwA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDY2FBeUZqczA1TDBTZ255
            YUJ1Y3JtNGJnditoTVhwQjZ2UDdIak5pdHhRClgvdXcwdjgvaEQ4V3QrSTF4dkR0
            UklXSGRoemdmNzhlSE9yYjd1cVIrcDAKLS0tIFQ3MFhPZEs4TUR0Tm1yY0ZqQmNi
            ZkIxQmlaWnhCWDB6TVNRVmpDOWE3WncKWbtFlTql4CblLIxPP8fUaTl4ODfdZHtc
            Ay9Yz/Ubgdwn0v2/E+flbCl/1TawLFXRbZHxsxfXTP3S12JJp1Zh2w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g4erccmqr8znqmhszfyq425l6dt9thq7vmllrn7z9yjfaug3putqlgs4ry
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-16T17:30:47Z"
    mac: ENC[AES256_GCM,data:TKocUTS8/fj5HsF/apzML3nCAXuAid2+p58NeZLSx8z0TuYgRT6FZqbIZ5TaW84iBHbwX/VqqTFDX2OSoqrSbSeemhxr0PqWcb5KqBgNDFljfTu5KksSWX9l3xuGsbh3IkmhdZZ7paGSlaQbnGwuLibStg+W4Gi2AgxVt6mpflc=,iv:74PDFFqZ+Czt6unv8qq+F3sTLpB1nc7+Pgzl4vLcdPg=,tag:jfBlX81MXEmW+kpxkFF+5Q==,type:str]
    version: 3.13.0
