---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m0s
  chart:
    spec:
      chart: grafana
      version: 7.3.9
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: kube-system
  values:
    envFromSecret: grafana-env
    image:
      tag: 12.1.0
    admin:
      existingSecret: grafana-credentials
    sidecar:
      dashboards:
        enabled: true
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: loki
            access: proxy
            basicAuth: false
            editable: true
            jsonData:
              tlsSkipVerify: true
            orgId: 1
            type: loki
            url: http://loki-gateway
          - name: prometheus
            access: proxy
            basicAuth: false
            editable: true
            jsonData:
              tlsSkipVerify: true
            orgId: 1
            type: prometheus
            url: http://mimir-nginx/prometheus
    alerting:
      contactpoints.yaml:
        apiVersion: 1
        contactPoints:
          - name: discord
            orgId: 1
            receivers:
              - uid: discord-webhook
                type: discord
                settings:
                  url: "${DISCORD_WEBHOOK_URL}"
                  username: Grafana Alerts
                  avatar_url: "https://avatars.githubusercontent.com/u/7195757?s=200&v=4"
                  message: |
                    **Alert:** {{`{{ .CommonLabels.alertname }}`}}
                    **Status:** {{`{{ .Status }}`}}
                    **Description:** {{`{{ .Annotations.description }}`}}
