---
- name: Check for calico namespace
  ansible.builtin.command: kubectl get namespace calico-system
  ignore_errors: true
  register: calico_namespace
- name: Install Calico
  ansible.builtin.shell: |
    kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/{{ kubernetes_calico_version }}/manifests/tigera-operator.yaml
  when: calico_namespace.rc != 0
- name: Update Calico
  ansible.builtin.shell: |
    kubectl replace -f https://raw.githubusercontent.com/projectcalico/calico/{{ kubernetes_calico_version }}/manifests/tigera-operator.yaml
  when: calico_namespace.rc == 0

- name: Create calico resources
  block:
    - name: Create custom resources
      ansible.builtin.template:
        src: files/custom-resources.yml
        dest: /tmp/custom-resources.yml
        mode: "0644"
    - name: Apply custom resources
      ansible.builtin.command: kubectl apply -f /tmp/custom-resources.yml
