---
- name: Validate kubernetes_calico_version
  ansible.builtin.assert:
    that:
      - kubernetes_calico_version is defined
      - kubernetes_calico_version is string
    fail_msg: "'kubernetes_calico_version' must be a string."
    success_msg: "'kubernetes_calico_version' is valid."
- name: Validate kubernetes_calico_cidr
  ansible.builtin.assert:
    that:
      - kubernetes_calico_cidr is defined
      - kubernetes_calico_cidr is string
    fail_msg: "'kubernetes_calico_cidr' must be a string."
    success_msg: "'kubernetes_calico_cidr' is valid."
