- name: Add docker repository
  block:
    - name: Add gpg key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian/gpg
    - name: Add docker repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable
        state: present
- name: Install docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
- name: Ensure docker is active
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ username }}"
    groups: docker
    append: true
  notify:
    - Reboot system
