---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: alloy-config
    namespace: monitoring
    files:
      - config/config.alloy
    options:
      disableNameSuffixHash: true
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
configurations:
  - kustomizeconfig.yaml
resources:
  - repository.yaml
  - release.yaml
