---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: monitoring
spec:
  interval: 5m0s
  chart:
    spec:
      chart: alloy
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: alloy
        namespace: kube-system
  values:
    alloy:
      clustering:
        enabled: true
      mounts:
        varlog: true
      configMap:
        create: false
        name: alloy-config
        key: config.alloy
