- name: Join cluster
  community.docker.docker_swarm:
    state: join
    join_token: "{{ hostvars['swarm-manager1'].join_tokens.Worker }}"
    remote_addrs:
      - "{{ hostvars['swarm-manager1'].ansible_host }}"
