---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir
  namespace: monitoring
spec:
  interval: 5m0s
  chart:
    spec:
      chart: mimir-distributed
      version: 5.8.0
      sourceRef:
        kind: HelmRepository
        name: mimir
        namespace: kube-system
  values:
    mimir:
      structuredConfig:
        limits:
          max_global_series_per_user: 2000000
          out_of_order_time_window: 5m
    distributor:
      replicas: 3
    alertmanager:
      replicas: 3
    ingester:
      replicas: 3
      zoneAwareReplication:
        enabled: false
      persistentVolume:
        size: 50Gi
    store_gateway:
      replicas: 3
      zoneAwareReplication:
        enabled: false
    minio:
      persistence:
        size: 50Gi
      serviceAccount:
        name: "mimir-minio-sa"
