---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir
  namespace: monitoring
spec:
  interval: 5m0s
  chart:
    spec:
      chart: mimir-distributed
      version: 5.8.0
      sourceRef:
        kind: HelmRepository
        name: mimir
        namespace: kube-system
  values:
    distributor:
      replicas: 1
    alertmanager:
      replicas: 1
    ingester:
      replicas: 2
      zoneAwareReplication:
        enabled: false
    store_gateway:
      replicas: 1
      zoneAwareReplication:
        enabled: false
    minio:
      serviceAccount:
        name: "mimir-minio-sa"
