apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-discord
    namespace: monitoring
type: Opaque
stringData:
    webhook_url: ENC[AES256_GCM,data:Z4hN8Pg3P+Ay0Z95xj2z0iS1qbyk75yKYW9O6IT/bkggUmQAuT/maroUg8yVhKRgU2hwsj8GcExWxf9rsCl3YJksi9qNK3Htl1e/3aLZxKNtpid/tSABdyusNIhN3uvodMVA/AO+7GMRG56QxglRM1piZkPUKuMNvg==,iv:e1CPklVfK9LFjPviRwfFzGgLMLDU/UflOCCYRTzoTkY=,tag:di+mudPaPTJFj2RnnKwM4w==,type:str]
sops:
    age:
        - recipient: age1g4erccmqr8znqmhszfyq425l6dt9thq7vmllrn7z9yjfaug3putqlgs4ry
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUkcwYVBmQmdBdlVFREtQ
            alRHT09TUWlJY2ZaZi9BUVU3ZXFYR0tlclNnCnc3THNrdWo3QWhzZlhsazNSOXRp
            UVkrVlhubHk4Q0thUzVYd2tEd1MwSmsKLS0tIEhDVmNyY3RadWpOTkY4RDZwUDBL
            TzA2NUZiNGtRM21wNkJuRFNlekFTQWsKXHD8jBlv00hV23XbBrTB8nETjfwyreYk
            Gu1JWBYx0aONIonVZ0MTHb1OsBsUBzljxSOjgAQubTmYenbQfinYYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T03:24:19Z"
    mac: ENC[AES256_GCM,data:IxMYX/RXZ0EAC0auJU84Errejt1a7rINeN+INv2jmbR7J/5eqyaZ7UcFUmo04E4Q8eFHhBWWuZ0Jo7JOo5qtjhmo5/ngK5Y3Fsp88ymW4qIi2m7k2nuWOx97oUsgFs5wCbwJ8DRdpqnbq197rxIcoVmpkPS7ppTj5YFm0Rq84Yk=,iv:3B2doNhjqWBC29Hm3sGALz/pens7AZ5NfaiPR2ncst4=,tag:+IfYIzBpUYAjYVmmfbE+JQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
