---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
  namespace: immich
spec:
  instances: 1
  imageName: tensorchord/cloudnative-vectorchord:16.14-1.1.1
  inheritedMetadata:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9187"
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-postgres-user
      dataChecksums: true
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
        - CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;
  postgresql:
    shared_preload_libraries:
      - vchord.so
    parameters:
      checkpoint_completion_target: "0.9"
      checkpoint_timeout: 15min
      max_wal_size: 2GB
  storage:
    storageClass: local-path
    size: 50Gi
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "2"
      memory: 2Gi
