apiVersion: v1
kind: Secret
metadata:
    name: immich-secrets
    namespace: immich
type: Opaque
stringData:
    immich-config.yaml: ENC[AES256_GCM,data:h97YNfLE1nMp0YiLO8+KUkTJbtc50+DrI+Prvt3pUxQylC2/ZtVOzm/jB4OEi9mpHBEhiBGAuIF4pHDwntRCHITv4DMGU93HyGyYVcKXcoZM+PCyl6c2yy1ePnwLgl1FlpYP8gg55Kf7U5vetKyhgpBnrgGTDJcn9ssqIm6UdU5/h3dQNZJWKRMAE1jJCnAvhgm0W/Y/ZJOKCHrz4EMVqyueOzDeK+Vjcea6hGHJgVlR9DhxKPkg6K+BC6cxkNmG4VlyuLUNaVUqeuKFs0YMmujuVGpxLNut91DNLfVfYms6PFVNrg+qLhoJB1f9yiHTxJFSUceHOC57yDHKYmGkIUvYOSfKZsxtgc0sA3QtvrF9Dkv3oO+zq5Hnipg4SMRvjKXQsGzXf+8bIsbx1BcZlPgAnazXOSsrgSmbWBOpuaJPhzCD4e4G3t0IoUImTwVCfvljXSjjRHcWwvqD9nioUQdpIw+hDLHIOOlAaUfXr4L+KeqJoQiA0XJoqGuSh6Q5k82tvm8mjQQ0giMiJ63+piyYG3BaZJ/dvaCOfszqBvZivOtbFriE5xgmCYkObuOBEek8ywn+gKyzdtIlYEluaXIyVQg7kNldny2aUPlGFSpTtdI1QTdQTVFEo0ttJ5D7WDvDqJVR5Uz3RzarIzYBnI9QBNwvAH7Plu0FfJ+mTK+bpsyPr2fQfrhsAVkycfcoBS/a8YyAmUT0dcXvZQKnH2wxCJs4nJUArG9j2Om5LrQm1YcuFA==,iv:7+0ufQjZAb7dWRdn7X/hXc503Di9rHuMm8gOQpNqyKA=,tag:MUoqiCjZIkM5d5O9h8q0ig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRcm4vcFk5NUZwR0kwbCtO
            bi8xUEZxTVdWNWc5ZWlva2Jrak9CblhqQVdRCmVRd01WTjFIYzRlTU1YYnVITVJE
            VEczdGxvNlRoU1BOOGt5TTc3bnh5R2cKLS0tIGhzZlpQTjZpak5JYkpRc2hjdzdz
            S0dTa01oRjdyV2c1RDFpRjZaNktKOEEKTOE0084AOPOhsDh5nTArPwL53S8gDRqq
            aBfdwiZJZZ5xgF9ChVdihHoR+zW7qDZDRGoHAqGPfXwvhh/OxpW9/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g4erccmqr8znqmhszfyq425l6dt9thq7vmllrn7z9yjfaug3putqlgs4ry
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-04T15:29:03Z"
    mac: ENC[AES256_GCM,data:0tGjZqVWtpol8d4oZ5v++8tRLiZ0Tgz35F/8rrh6jhk87bSaomO7bwEi/Nu6vgODVMiy5YD267+OMj385R+EDp2ewwtoL+RdYRzSLpsOSWFpywAGqDJw65I/A7AdE66JOvu6Yq+9bpfYkQTNr/00eL9AZ5Tsd9wiYxWPEazQpQ0=,iv:AjFMcBvDCXbqev1dfWWE8yXZWQT2zb5QaBMcAOkt4kk=,tag:ikrILPUcTVHeJA2FYbqjPA==,type:str]
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: immich-postgres-user
    namespace: immich
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:MQl7KIhp,iv:NvNRNa4MS8pShRLYDk2HqJI3+VQTEKntCMp+vZySDTo=,tag:H8H3P/wzSJ1+3ZQ3+OR8Dw==,type:str]
    password: ENC[AES256_GCM,data:lI9VWg6KRdRi9LlH+uOvhI/Nwb6OnrEQutW8r0uFTeRpGfqAlFuV/yXKIyw93Ybj,iv:HPsZoj+qj1eLK3sb33qp+xKjACVn6Ww0TBhdgcwIYmo=,tag:x9UFUuTIXm5+PLRqDgU92g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRcm4vcFk5NUZwR0kwbCtO
            bi8xUEZxTVdWNWc5ZWlva2Jrak9CblhqQVdRCmVRd01WTjFIYzRlTU1YYnVITVJE
            VEczdGxvNlRoU1BOOGt5TTc3bnh5R2cKLS0tIGhzZlpQTjZpak5JYkpRc2hjdzdz
            S0dTa01oRjdyV2c1RDFpRjZaNktKOEEKTOE0084AOPOhsDh5nTArPwL53S8gDRqq
            aBfdwiZJZZ5xgF9ChVdihHoR+zW7qDZDRGoHAqGPfXwvhh/OxpW9/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g4erccmqr8znqmhszfyq425l6dt9thq7vmllrn7z9yjfaug3putqlgs4ry
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-04T15:29:03Z"
    mac: ENC[AES256_GCM,data:0tGjZqVWtpol8d4oZ5v++8tRLiZ0Tgz35F/8rrh6jhk87bSaomO7bwEi/Nu6vgODVMiy5YD267+OMj385R+EDp2ewwtoL+RdYRzSLpsOSWFpywAGqDJw65I/A7AdE66JOvu6Yq+9bpfYkQTNr/00eL9AZ5Tsd9wiYxWPEazQpQ0=,iv:AjFMcBvDCXbqev1dfWWE8yXZWQT2zb5QaBMcAOkt4kk=,tag:ikrILPUcTVHeJA2FYbqjPA==,type:str]
    version: 3.13.0
