- name: Create unifi_console_usr secret
  community.docker.docker_secret:
    name: unifi_console_usr
    data: "{{ unifi_console_usr }}"
    state: present
- name: Create unifi_console_pwd secret
  community.docker.docker_secret:
    name: unifi_console_pwd
    data: "{{ unifi_console_pwd }}"
    state: present
- name: Create pve_usr secret
  community.docker.docker_secret:
    name: pve_usr
    data: "{{ pve_usr }}"
    state: present
- name: Create pve_pwd secret
  community.docker.docker_secret:
    name: pve_pwd
    data: "{{ pve_pwd }}"
    state: present
