---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external.yaml
  - pihole.yaml
  - whoami.yaml
  - renovate.yaml
  - cloudflare-tunnels.yaml
  - jellyfin.yaml
  - foundryvtt.yaml
  - valheim.yaml
