---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: intel-gpu-device-plugin
  namespace: flux-system
spec:
  interval: 2m
  retryInterval: 2m
  path: ./kubernetes/infra/controllers/intel-device-plugins/gpu
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: intel-device-plugins-operator
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
