---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings

layout:
    servers:
        style: row
        columns: 3
quicklaunch:
    searchDescriptions: true
    hideInternetSearch: true
    hideVisitURL: true
