---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/widgets

- unifi_console:
    url: "https://unifi.{{HOMEPAGE_VAR_DOMAIN}}"
    username: "{{HOMEPAGE_FILE_UNIFI_CONSOLE_USR}}"
    password: "{{HOMEPAGE_FILE_UNIFI_CONSOLE_PWD}}"
- search:
    provider: duckduckgo
    target: _blank
