- name: Ensure folders exist
  ansible.builtin.file:
    path: /swarm/volumes/traefik
    state: directory
    mode: '0644'
- name: Copy files
  ansible.builtin.copy:
    src: files/
    dest: /swarm/volumes/traefik/
    mode: '0644'
- name: Ensure letsencrypt volume exists
  ansible.builtin.file:
    path: /swarm/volumes/traefik/letsencrypt
    state: directory
    mode: '0644'
- name: Create secrets
  ansible.builtin.import_tasks: secrets.yml
- name: Deploy traefik
  community.docker.docker_stack:
    state: present
    name: traefik
    compose:
      - /swarm/volumes/traefik/docker-compose.yml
  environment:
    STACK_TRAEFIK_DOMAIN: "{{ domain }}"
    STACK_TRAEFIK_EMAIL: "{{ email }}"
