version: "3.8"

services:
  homepage:
    image: ghcr.io/benphelps/homepage:main
    environment:
        - HOMEPAGE_FILE_UNIFI_CONSOLE_USR=/run/secrets/unifi_console_usr
        - HOMEPAGE_FILE_UNIFI_CONSOLE_PWD=/run/secrets/unifi_console_pwd
        - HOMEPAGE_VAR_DOMAIN=${STACK_HOMEPAGE_DOMAIN}
        - HOMEPAGE_FILE_PVE_USR=/run/secrets/pve_usr
        - HOMEPAGE_FILE_PVE_PWD=/run/secrets/pve_pwd
        - HOMEPAGE_FILE_TRUENAS_API_KEY=/run/secrets/truenas_api_key
    secrets:
        - unifi_console_pwd
        - unifi_console_usr
        - pve_usr
        - pve_pwd
        - truenas_api_key
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/app/config
    networks:
      - proxy
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy

        - traefik.http.routers.homepage.rule=Host(`homepage.${STACK_HOMEPAGE_DOMAIN}`)
        - traefik.http.routers.homepage.entrypoints=websecure
        - traefik.http.routers.homepage.tls.certresolver=primary
        - traefik.http.routers.homepage.tls.domains[0].main=${STACK_HOMEPAGE_DOMAIN}
        - traefik.http.routers.homepage.tls.domains[0].sans=*.${STACK_HOMEPAGE_DOMAIN}
        - traefik.http.routers.service=homepage

        - traefik.http.services.homepage.loadbalancer.server.port=3000
secrets:
  unifi_console_usr:
    file: .unifi_console_usr.secret
  unifi_console_pwd:
    file: .unifi_console_pwd.secret
  pve_usr:
    file: .pve_usr.secret
  pve_pwd:
    file: .pve_pwd.secret
  truenas_api_key:
    file: .truenas_api_key.secret
networks:
  proxy:
    external: true
