---
- name: Delete user
  ansible.builtin.user:
    name: "{{ user_name }}"
    state: absent
    remove: true
    force: true
- name: Delete group
  ansible.builtin.group:
    state: absent
    name: "{{ group_name }}"
