---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crds.yaml
  - cert-manager.yaml
  - local-path-provisioner.yaml
  - cloudnative-pg.yaml
  - grafana-operator.yaml
  - intel-device-plugins-operator.yaml
  - intel-gpu-device-plugin.yaml
  - nfs-csi.yaml
  - cilium.yaml
  - metrics-server.yaml
  - certs.yaml
  - gateway.yaml
  - vpn.yaml
  - monitoring.yaml
  - loki.yaml
  - mimir.yaml
  - alloy.yaml
  - grafana.yaml
  - otel-collector.yaml
  - authentik.yaml
