---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vpn
  namespace: flux-system
spec:
  interval: 2m
  retryInterval: 2m
  path: ./kubernetes/infra/network/vpn
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cilium
    - name: nfs-csi
    - name: gateway
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
