---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - whoami-template.yaml
  - jellyfin-template.yaml
  - homepage-template.yaml
  - home-assistant-template.yaml
  - immich-template.yaml
