apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:sSCWQNH4nL3o/hna8grAhyr6/ipytKp3FShdjO4UaRZ5J+JVhNUZuYU2Nwo6DT8AMyb6ISqdM0Z7AAOCxN4Nuw==,iv:0OXJQILctYDql/MAx9JZfeyyAOEgv54Fy8vt2ayCMR4=,tag:jYE3AOUXPTNBgYYYQ+xedg==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:gGlcsH4CrmY7LLiJHoI2E2bamIQfjIywMnOnByaH0awt8TZ8at7vubfMozxJrdW/,iv:rCITuvhtT7ECCbZMw7ZUBBS0JaBNhf/M/+nxlUKm2gw=,tag:7cjO/nWPWFidmYXjNWJMbw==,type:str]
    password: ENC[AES256_GCM,data:NAuwTa6f50iTx9yppbynLc0mJhxKojngGFgv55crgkW1sLsZT6tI/2IqudNvxXB3,iv:kNSIn3i3DiTUuujKnDm/MRkjCenCQO1OjvAEQ/jRBdA=,tag:9XTCJP248f+YNWEKqUe7tg==,type:str]
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:g9BHKlsuM3/bFXnysgqHps0ECVTyDVVi7YdLxA==,iv:ThiU4KtiYpjht39qtRX1NWTgNbskvTVBC1maaHLQl84=,tag:g7bBiwPuudSgmepvC5beGA==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:C+MQiGDf8SqTfVV+6ofzdTMoYVdsM9M7eyR5mYXjwmE9w7kb5e0QGLT0l7ugKv/L,iv:iubO9PmF4IELkKvqFbXz4QHNRU4D8X8h1HJThLQffm0=,tag:hiaqEh2e2TTQBR5XfgXcrg==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:ZV4i1lk18kJmtOv9SEtmcjcQD11389aMPpPnz3J/Pfh+In3rS8qFE4/XSWr/K0b9,iv:5qecH38IXJcUe717nO3HFYHilJvAEnKlteXaM3AFB2U=,tag:44iWCP/ADrZzxTEvDYqebA==,type:str]
    JELLYFIN_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:VOD1CrWStBOzLYLyfP2NzrlRpMFu9cRgvQeZSlnJBLv945km2POFsb0l6r1Dhyfio4JRYfS80f5twwhVd6+Bng==,iv:rEUc7I5VGCV0mbzAvsL5HA8PbnLjM4JSkMUl3z/Zv70=,tag:8eDEWq2saZ2LbHEit+WMVQ==,type:str]
    JELLYFIN_TEST_PASSWORD: ENC[AES256_GCM,data:H4gPhw==,iv:9TSMishipo14RDOTZpxMknc1cf630vIyj3jKZX+8kzw=,tag:Q6nr9mAPmeOEjNuL/j/QjQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVaTluMlVSQ1A2S3FOY21D
            cGQ3U245UGwvVWU4cnE5Z1ZkTFpzVG4zc0I4CmpQUjhLc2t0Z24vRnk5bUdsa2Uz
            a0NSazJJZXRDcEVjRTlXRTNqcGJ4T00KLS0tIDZFemM1ZnNEZEdDdXVGcTMra1Jl
            MVd5UHJ2VTBMUUJ4NHZMMjFaVG9uVXMKsQgi9BeJtDPHKqwFW2sZdJVxmE3oGgaF
            891+tEaVvdv2JQhg2oPGJfmVmPcAaORG/l1X/vt119z6yPukaDy0hA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g4erccmqr8znqmhszfyq425l6dt9thq7vmllrn7z9yjfaug3putqlgs4ry
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T18:39:07Z"
    mac: ENC[AES256_GCM,data:ymq5ylTCUPldkkFzwk2HJuH5BXcV8Ug5G8bRaXPSmfG5DUCaYe+lpDt6KLW0DD6GZaEsvrIx1BnGxCa6nTeDrfl4wXcqOsEFwZhU0j8kJuM7ErHRLeyqJG4DKFvDGOEm9CYo4XG1OCcp3hRFf73qv9OOvZ7MukfgWfZoOnKbkI0=,iv:7IJa75Gr1G5m7H8VjcxjqUI8N21hTd/0JsCJHacwTuE=,tag:hQ5eGVQUpuGpq9pltWh1eg==,type:str]
    version: 3.13.0
