---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  interval: 5m0s
  url: https://jellyfin.github.io/jellyfin-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  interval: 5m
  releaseName: jellyfin
  chart:
    spec:
      chart: jellyfin
      sourceRef:
        kind: HelmRepository
        name: jellyfin
        namespace: jellyfin
      version: "2.1.0"
  valuesFrom:
    - kind: ConfigMap
      name: jellyfin-values
