# This task is used to create a cluster of virtual machines in proxmox.
---
- name: Include validation tasks
  ansible.builtin.import_tasks: validate.yml

- name: Execute terraform
  community.general.terraform:
    project_path: "{{ lookup('ansible.builtin.env', 'WORKSPACE_FOLDER') }}/terraform"
    state: "{{ 'absent' if provision_cluster_operation == 'destroy' else 'present' }}"
    complex_vars: true
    variables:
      ssh_key: "{{ provision_cluster_ssh_proxmox_private_key }}"
      image: "{{ provision_cluster_image_name }}"
      network_config:
        gateway: "{{ provision_cluster_networking_gateway_ip }}"
        ips: "{{ provision_cluster_ips }}"
    force_init: true
  environment:
    PM_API_TOKEN_ID: "{{ provision_cluster_proxmox_token_id }}"
    PM_API_TOKEN_SECRET: "{{ provision_cluster_proxmox_token_secret }}"
    PM_API_URL: "{{ provision_cluster_proxmox_api_url }}"
  register: terraform_output
- name: Print terraform output
  ansible.builtin.debug:
    msg: "{{ terraform_output.stdout_lines }}"
