---
- name: Validate operation
  ansible.builtin.assert:
    that:
      - provision_cluster_operation in ['apply', 'destroy']
    fail_msg: "'provision_cluster_operation' must be 'apply' or 'destroy'."
    success_msg: "'provision_cluster_operation' is valid."
- name: Validate image name
  ansible.builtin.assert:
    that:
      - provision_cluster_image_name is string
      - provision_cluster_image_name is defined
    fail_msg: "'provision_cluster_image_name' must be a string."
    success_msg: "'provision_cluster_image_name' is valid."
- name: Validate proxmox token id
  ansible.builtin.assert:
    that:
      - provision_cluster_proxmox_token_id is string
      - provision_cluster_proxmox_token_id is defined
    fail_msg: "'provision_cluster_proxmox_token_id' must be a string."
    success_msg: "'provision_cluster_proxmox_token_id' is valid."
- name: Validate proxmox token secret
  ansible.builtin.assert:
    that:
      - provision_cluster_proxmox_token_secret is string
      - provision_cluster_proxmox_token_secret is defined
    fail_msg: "'provision_cluster_proxmox_token_secret' must be a string."
    success_msg: "'provision_cluster_proxmox_token_secret' is valid."
- name: Validate proxmox api url
  ansible.builtin.assert:
    that:
      - provision_cluster_proxmox_api_url is string
      - provision_cluster_proxmox_api_url is defined
    fail_msg: "'provision_cluster_proxmox_api_url' must be a string."
    success_msg: "'provision_cluster_proxmox_api_url' is valid."
- name: Validate ssh private key
  ansible.builtin.assert:
    that:
      - provision_cluster_ssh_proxmox_private_key is string
      - provision_cluster_ssh_proxmox_private_key is defined
    fail_msg: "'provision_cluster_ssh_proxmox_private_key' must be a string."
    success_msg: "'provision_cluster_ssh_proxmox_private_key' is valid."
- name: Validate networking gateway ip
  ansible.builtin.assert:
    that:
      - provision_cluster_networking_gateway_ip is string
      - provision_cluster_networking_gateway_ip is defined
    fail_msg: "'provision_cluster_networking_gateway_ip' must be a string."
    success_msg: "'provision_cluster_networking_gateway_ip' is valid."
- name: Validate ips
  ansible.builtin.assert:
    that:
      - provision_cluster_ips is iterable
      - provision_cluster_ips is defined
    fail_msg: "'provision_cluster_ips' must be iterable."
    success_msg: "'provision_cluster_ips' is valid."
