---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-vars
  namespace: flux-system
data:
  cluster_domain: "lab.petebeegle.com"
  cluster_env: "production"
  gateway_internal_ip: "192.168.30.241"
  gateway_passthrough_ip: "192.168.30.242"
  nfs_server: "192.168.30.99"
  letsencrypt_server: "https://acme-v02.api.letsencrypt.org/directory"
  wildcard_cert_name: "wildcard-lab-petebeegle-com"
