---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: onepassword-items
  namespace: flux-system
spec:
  interval: 2m
  retryInterval: 2m
  path: ./kubernetes/clusters/production/onepassword-items
  prune: true
  wait: true
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: onepassword-operator
    - name: app-access-broker
    - name: app-cloudflare-tunnels
    - name: app-foundryvtt
    - name: app-home-assistant
    - name: app-immich
    - name: app-jellyfin
    - name: app-pihole
    - name: app-renovate
    - name: app-valheim
    - name: private-source
    - name: authentik
    - name: cert-manager
    - name: grafana
    - name: monitoring
    - name: vpn
