apiVersion: v1
kind: Secret
metadata:
    name: grafana-env
    namespace: monitoring
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:ciYuP1QzZyYNIpZTHpAijR8tRC/PFrtMglPwybfewnUpvDhS+lDtQCvW6BFcvFnQPR9KCtU6WKNlSh1gY/xNUQhSXBAQLyZYZ4W2BhJSt+qqiBRD4N9ZgC0q1vbTYmWkx+leD674HyDE6Vi8ZgYSgUbScpxVl2jb/A==,iv:Uhd7mEgGlSkt1bn3Y23bJM+Z0SR7upNQUfhtqsGv+W8=,tag:GT+i6fCrhlI5aWB9w6b5DA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUE9YRmgrMHVuL3pjTFZp
            OTllL08yaDFXVnozUC9uVUNjRWZJVTFYODNJCjdIWEQrbEZ0dEdpTXBFbTBKVEt3
            U21tNE9iZHdRVVUrZEZ2Zmk3NDlZbUkKLS0tIFBESjdnTndIcGIrLzAwZG1zMVg3
            d1ZmL2xvaTRHSTJlUEIweWtDK280RFkKicr85T2h59lP2/xFJPpWqIxmZzyyiLGi
            mGJ1py0zFHdvHjHgtJWnLfjALsu+2S1yLhRfgqefStgmF0+IbjKHRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g4erccmqr8znqmhszfyq425l6dt9thq7vmllrn7z9yjfaug3putqlgs4ry
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-16T17:30:47Z"
    mac: ENC[AES256_GCM,data:PTkalU6yfZibN5RGXkRNO7GmRBjg9tcBxgh6w7Kd8ZFo+9e2Hw+SfH+2dAyEG0/3J5h/wvRuEG0BwU7jc/9vGkCoLUWOHQ7E2lWVulsxV14YLt1PDMDnrXRcZAa0/qU0fXL/1DwrAITBcYTW5P+KwpOt3Z6YvglaqEYWW7zgiPk=,iv:T0EF6XIP9dG0TxXaTE2G+gm4czk2h7cXvFcuRpXYXzk=,tag:FTKlKfN8OJ8vF/L7vFsC/Q==,type:str]
    version: 3.13.0
