apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-secrets
    namespace: jellyfin
type: Opaque
stringData:
    JELLYFIN_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:4yTnQCUDHBKOV/PHiITDB3vYD+Q0eDzRKp/K4UeSyGu+dohM7G8IwQN0rK25WWcpmDk6mUkohlEPeIm9YJhvwg==,iv:psRzeTVjhw/3y519Bb3sPTYetUnBkCvGhCiUPMdjMy0=,tag:Z0emUrATGqGm7wFqa2dsLA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWk55OVQ4cWNUaVlFamdw
            c0hteXRKdHpnN2FtMk9wSm4vSTZEaWxBZUNjCkdpL0U4eXUyY200ZEl6UXQ2dWNz
            bEVvTFYwbHUrSVZXSmN4TnNOb1pPdEEKLS0tIGViRXp6SFVwQU9FYzBka0IvR3JV
            VTBON0ZBZDVpQnVxMlQrMXpNNjFJVGsKhJuPsxtX4xDCMtccH6pF0luC7YHT+l1V
            fn6ED8sLot/9cAqbuPIoN87oADC2PbxZNr/LYRjRZ/irMTdxMOPx9g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g4erccmqr8znqmhszfyq425l6dt9thq7vmllrn7z9yjfaug3putqlgs4ry
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T00:42:05Z"
    mac: ENC[AES256_GCM,data:HOh7MnljtPrDcZ9fRx7fXjf/HVbdDg41fm6jeILz1aq3liIRah4kNNLViIvQIBnd+dfVDctI9eogNOSqOC7xwUWyuuxVknJl9eCgKCtjwtQU34LloF4A5e8I6PYuEVmSs0OvY2Zw5Ho7Svt0EKbLaPrX6Y7ET6M+4LWNBCtgg+8=,iv:GbZPW9xJy9CyBzj5MG/ng7G9rHdsO94z/DgVvukdhhw=,tag:47ChUwzO5NOnaxdw8trQ3g==,type:str]
    version: 3.13.0
