persistence:
  config:
    enabled: true
    existingClaim: jellyfin-config-v2
    storageClass: nfs-csi-storage
  media:
    enabled: false
startupProbe:
  httpGet:
    path: /health
    port: http
  failureThreshold: 60
  periodSeconds: 10
  timeoutSeconds: 5
livenessProbe:
  httpGet:
    path: /health
    port: http
  failureThreshold: 6
  periodSeconds: 10
  timeoutSeconds: 5
readinessProbe:
  httpGet:
    path: /health
    port: http
  failureThreshold: 6
  periodSeconds: 10
  timeoutSeconds: 5
volumes:
  - name: custom-media
    nfs:
      server: ${nfs_server}
      path: /volume1/Media/Jellyfin
volumeMounts:
  - name: custom-media
    mountPath: /custom-media
