persistence:
  config:
    enabled: true
    existingClaim: jellyfin-config-v2
    storageClass: nfs-csi-storage
  media:
    enabled: false
service:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8096"
    prometheus.io/path: /metrics
metrics:
  enabled: true
  serviceMonitor:
    enabled: false
startupProbe:
  tcpSocket:
    port: http
  failureThreshold: 60
  periodSeconds: 10
  timeoutSeconds: 5
livenessProbe:
  httpGet: null
  tcpSocket:
    port: http
  failureThreshold: 6
  periodSeconds: 10
  timeoutSeconds: 5
readinessProbe:
  httpGet: null
  tcpSocket:
    port: http
  failureThreshold: 6
  periodSeconds: 10
  timeoutSeconds: 5
volumes:
  - name: custom-media
    nfs:
      server: ${nfs_server}
      path: /volume1/Media/Jellyfin
volumeMounts:
  - name: custom-media
    mountPath: /custom-media
