---
apiVersion: v1
kind: Service
metadata:
  name: proxmox
  namespace: proxmox
spec:
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8006
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: proxmox
  namespace: proxmox
  labels:
    kubernetes.io/service-name: proxmox
addressType: IPv4
ports:
  - name: https
    protocol: TCP
    port: 8006
endpoints:
  - addresses:
      - 192.168.3.2
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: proxmox-route
  namespace: proxmox
spec:
  parentRefs:
    - name: passthrough
      namespace: gateway
  hostnames:
    - proxmox.lab.petebeegle.com
  rules:
    - backendRefs:
        - name: proxmox
          port: 443
