---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  interval: 5m
  releaseName: traefik
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: kube-system
      version: "v32.1.1"
  values:
    providers:
      kubernetesGateway:
        enabled: true
      kubernetesIngress:
        enabled: false
    gateway:
      enabled: true
      annotations:
        cert-manager.io/issuer: selfsigned-issuer
      listeners:
        web:
          namespacePolicy: All
        websecure:
          namespacePolicy: All
          hostname: whoami.docker.localhost
          port: 8443
          protocol: HTTPS
          certificateRefs:
            - name: whoami-tls
    ingressRoute:
      dashboard:
        enabled: true
