---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-crds
  namespace: kube-system
spec:
  url: https://prometheus-community.github.io/helm-charts
  interval: 1m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-crds
  namespace: kube-system
spec:
  interval: 5m0s
  chart:
    spec:
      chart: prometheus-operator-crds
      version: 23.0.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-crds
        namespace: kube-system
