---
- name: Validate kubeconfig
  block:
    - name: Check kubeconfig file existence at $HOME/.kube/config
      ansible.builtin.stat:
        path: "{{ lookup('env', 'HOME') }}/.kube/config"
      register: kubeconfig_file

    - name: Assert kubeconfig file exists
      ansible.builtin.assert:
        that:
          - kubeconfig_file.stat.exists
        fail_msg: kubeconfig file does not exist at $HOME/.kube/config.
        success_msg: kubeconfig file exists at $HOME/.kube/config.
- name: Validate kubernetes_nfs_csi_version
  ansible.builtin.assert:
    that:
      - kubernetes_nfs_csi_version is string
      - kubernetes_nfs_csi_version is defined
    fail_msg: "'kubernetes_nfs_csi_version' must be a string."
    success_msg: "'kubernetes_nfs_csi_version' is valid."
- name: Validate kubernetes_nfs_csi_server
  ansible.builtin.assert:
    that:
      - kubernetes_nfs_csi_server is string
      - kubernetes_nfs_csi_server is defined
    fail_msg: "'kubernetes_nfs_csi_server' must be a string."
    success_msg: "'kubernetes_nfs_csi_server' is valid."
- name: Validate kubernetes_nfs_csi_share
  ansible.builtin.assert:
    that:
      - kubernetes_nfs_csi_share is string
      - kubernetes_nfs_csi_share is defined
    fail_msg: "'kubernetes_nfs_csi_share' must be a string."
    success_msg: "'kubernetes_nfs_csi_share' is valid."
