---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-discord
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager-discord
  template:
    metadata:
      labels:
        app: alertmanager-discord
    spec:
      containers:
        - name: alertmanager-discord
          image: rogerrum/alertmanager-discord:latest
          ports:
            - containerPort: 9094
          env:
            - name: DISCORD_USERNAME
              value: "Alertmanager"
            - name: DISCORD_WEBHOOK
              valueFrom:
                secretKeyRef:
                  name: alertmanager-discord
                  key: webhook_url
            - name: PORT
              value: "9094"
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
