---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  interval: 5m
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: kube-system
      version: "v1.17.0"
  values:
    crds:
      enabled: true
    config:
      enableGatewayAPI: true
