apiVersion: v1
kind: Secret
metadata:
    name: cloudflare
    namespace: kube-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:4iQ+p9ENxLRTmlYTDDbDxs64g3z85dPdz5GKQi+T8pD67fIX/VX5VQ==,iv:7EZgPVg54TKCnH7WcAJeBaH7YbmRbq5gdciQqP+CMGs=,tag:HNCSBuaZEfFjZmNWTvfqvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g4erccmqr8znqmhszfyq425l6dt9thq7vmllrn7z9yjfaug3putqlgs4ry
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWR3pobDB1UEUweXo5Y01L
              Nnd1UTlEYkc3Zk1jL2pENlFieDlnRWhNL3hVCktBZ0hyUFFkcHZOZE9YUGhncWQ4
              Y3VMWitYdXVGNVMrZ2xkQ2JUQ0p4MmMKLS0tIEkxYlpaUEFuamlBWlhVUDd3OGQ0
              WnRKaWxWRkRSU0I5bVhZclYxQUZZek0KJDUNF5AoVcBxieMtTttppkZijMchQ+L6
              k2v4h/9bbcFtg0p1LVcIpj8Fb2omK62b7RbBpm1y3Cdzj1OBVzTJZw==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-17T02:40:46Z"
    mac: ENC[AES256_GCM,data:iSIBMc4b6E/AbZfRrcCVMd8eTkoZuIubwcT73UNWitvCDZlSkxg2+/8Gr7bwUSkgTbnY/3uSc8iQFl7C4eLPV8B5UqisPHUxCkQhD3Qi5bRr7JpsauM1+btAbUH42TCNx7WOs1vPbfBHMYuGsdvCojePU1wCh/Js5INfLtaC9fE=,iv:7a+/t5WTgdlNY5i8yzWzXQA545QMK56CVn9jD2BirkU=,tag:PLZtfiSDOJi76LyhshYP2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
