---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 1h
  releaseName: pihole
  chart:
    spec:
      chart: pihole
      version: 2.27.0
      sourceRef:
        kind: HelmRepository
        name: pihole
        namespace: flux-system
  values:
    serviceWeb:
      type: ClusterIP

    serviceDns:
      loadBalancerIP: 192.168.3.250
      annotations:
        cilium.io/alias: pihole-svc
      type: LoadBalancer

    admin:
      existingSecret: pihole-admin-password
