{
 "title": "Flux Cluster Stats",
 "tags": [ "flux" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(gotk_resource_info,exported_namespace)"
    }
   },
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Cluster Reconcilers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(gotk_resource_info{namespace=~\"$namespace\", customresource_kind=~\"Kustomization|HelmRelease\",job=\"prometheus.scrape.pods\"})"
    }
   ]
  },
  {
   "title": "Failing Reconcilers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(gotk_resource_info{namespace=~\"$namespace\",customresource_kind=~\"Kustomization|HelmRelease\",ready=\"False\",job=\"prometheus.scrape.pods\"})"
    }
   ]
  },
  {
   "title": "Kubernetes Manifests Sources",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(gotk_resource_info{namespace=~\"$namespace\", customresource_kind=~\"GitRepository|HelmRepository|Bucket|OCIRepository\",job=\"prometheus.scrape.pods\"})"
    }
   ]
  },
  {
   "title": "Failing Sources",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(gotk_resource_info{namespace=~\"$namespace\", customresource_kind=~\"GitRepository|HelmRepository|Bucket|OCIRepository\", ready=\"False\",job=\"prometheus.scrape.pods\"})"
    }
   ]
  },
  {
   "title": "Reconciler Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(gotk_reconcile_duration_seconds_sum{namespace=~\"$namespace\",kind=~\"Kustomization|HelmRelease\", job=\"prometheus.scrape.pods\"}[5m])) by (kind)\n/\n  sum(rate(gotk_reconcile_duration_seconds_count{namespace=~\"$namespace\",kind=~\"Kustomization|HelmRelease\", job=\"prometheus.scrape.pods\"}[5m])) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Source Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(gotk_reconcile_duration_seconds_sum{namespace=~\"$namespace\",kind=~\"GitRepository|HelmRepository|Bucket|OCIRepository\",job=\"prometheus.scrape.pods\"}[5m])) by (kind)\n/\n  sum(rate(gotk_reconcile_duration_seconds_count{namespace=~\"$namespace\",kind=~\"GitRepository|HelmRepository|Bucket|OCIRepository\",job=\"prometheus.scrape.pods\"}[5m])) by (kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster reconciliation readiness ",
     "type": "table",
     "gridPos": { "h": 22, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "gotk_resource_info{namespace=~\"$namespace\",customresource_kind=~\"Kustomization|HelmRelease\",job=\"prometheus.scrape.pods\"}"
      }
     ]
    },
    {
     "title": "Source acquisition readiness ",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "gotk_resource_info{namespace=~\"$namespace\", customresource_kind=~\"GitRepository|HelmRepository|Bucket|OCIRepository\",job=\"prometheus.scrape.pods\"}"
      }
     ]
    },
    {
     "title": "Suspended Objects",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 32 },
     "targets": [
      {
       "expr": "gotk_resource_info{namespace=~\"$namespace\",suspended=\"true\",job=\"prometheus.scrape.pods\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Timing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster reconciliation duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(gotk_reconcile_duration_seconds_sum{namespace=~\"$namespace\",kind=~\"Kustomization|HelmRelease\",job=\"prometheus.scrape.pods\"}[5m])) by (kind, name)\n/\n  sum(rate(gotk_reconcile_duration_seconds_count{namespace=~\"$namespace\",kind=~\"Kustomization|HelmRelease\",job=\"prometheus.scrape.pods\"}[5m])) by (kind, name)",
       "legendFormat": "{{kind}}/{{name}}"
      }
     ]
    },
    {
     "title": "Source acquisition duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(gotk_reconcile_duration_seconds_sum{namespace=~\"$namespace\",kind=~\"GitRepository|HelmRepository|Bucket|OCIRepository\",job=\"prometheus.scrape.pods\"}[5m])) by (kind, name)\n/\n  sum(rate(gotk_reconcile_duration_seconds_count{namespace=~\"$namespace\",kind=~\"GitRepository|HelmRepository|Bucket|OCIRepository\",job=\"prometheus.scrape.pods\"}[5m])) by (kind, name)",
       "legendFormat": "{{kind}}/{{name}}"
      }
     ]
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Flux Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"kustomize-controller\"}"
    }
   ]
  }
 ]
}