---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  interval: 5m
  releaseName: traefik
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: kube-system
      version: "34.1.0"
  # https://github.com/traefik/traefik-helm-chart/blob/master/traefik/VALUES.md
  values:
    deployment:
      replicas: 3
    providers:
      kubernetesGateway:
        enabled: true
      kubernetesIngress:
        enabled: false
    gateway:
      enabled: true
      annotations:
        cert-manager.io/issuer: cloudflare
      listeners:
        web:
          namespacePolicy: All
        websecure:
          namespacePolicy: All
          hostname: "*.lab.petebeegle.com"
          port: 8443
          protocol: HTTPS
          certificateRefs:
            - name: wildcard-lab-petebeegle-com
    ingressRoute:
      dashboard:
        enabled: true
    metrics:
      prometheus:
        service:
          enabled: true
        disableAPICheck: false # Disable API check for Prometheus
        serviceMonitor:
          enabled: true
          namespace: monitoring
          metricRelabelings:
            - sourceLabels: [__name__]
              separator: ;
              regex: ^fluentd_output_status_buffer_(oldest|newest)_.+
              replacement: $1
              action: drop
          relabelings:
            - sourceLabels: [__meta_kubernetes_pod_node_name]
              separator: ;
              regex: ^(.*)$
              targetLabel: nodename
              replacement: $1
              action: replace
          jobLabel: traefik
          interval: 30s
          honorLabels: true
      prometheusRule:
        enabled: true
        rules:
          - alert: TraefikDown
            expr: up{job="traefik"} == 0
            for: 5m
            labels:
              context: traefik
              severity: warning
            annotations:
              summary: "Traefik Down"
              description: "{{ $labels.pod }} on {{ $labels.nodename }} is down"
      addEntryPointsLabels: true
      addRouterLabels: true
      addServicesLabels: true
    logs:
      access:
        enabled: true
        format: json
      general:
        format: json
