- name: Probe peers
  when: inventory_hostname == groups.gluster_nodes[0]
  ansible.builtin.command: gluster peer probe {{ item }}
  loop: "{{ groups.workers }}"
  changed_when: false
- name: Create volume
  when: inventory_hostname == groups.gluster_nodes[0]
  ansible.builtin.command: >
    gluster volume create {{ volume_name }} replica 3 \
    {{ groups.gluster_nodes[0] }}:/glusterfs/bricks/{{ groups.gluster_nodes[0] }}/brick \
    {{ groups.gluster_nodes[0] }}:/glusterfs/bricks/{{ groups.gluster_nodes[0] }}/brick \
    {{ groups.gluster_nodes[1] }}:/glusterfs/bricks/{{ groups.gluster_nodes[1] }}/brick \
    force
  changed_when: false
- name: Secure volume
  when: inventory_hostname == groups.gluster_nodes[0]
  ansible.builtin.command: >
    gluster volume set {{ volume_name }} auth.allow  \
    {{ groups.gluster_nodes[0] }},{{ groups.gluster_nodes[1] }},{{ groups.gluster_nodes[2] }}
  changed_when: false
- name: Start volume
  when: inventory_hostname == groups.gluster_nodes[0]
  ansible.builtin.command: gluster volume start {{ volume_name }}
  changed_when: false
