---
apiVersion: v1
kind: Service
metadata:
  name: synology
  namespace: external
spec:
  ports:
    - name: https
      protocol: TCP
      appProtocol: https
      port: 5001
      targetPort: 5001
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: synology
  namespace: external
  labels:
    kubernetes.io/service-name: synology
addressType: IPv4
ports:
  - name: https
    protocol: TCP
    appProtocol: https
    port: 5001
endpoints:
  - addresses:
      - ${nfs_server}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: synology-route
  namespace: external
spec:
  parentRefs:
    - name: internal
      namespace: gateway
      sectionName: synology-https-gateway
  hostnames:
    - synology.petebeegle.com
  rules:
    - backendRefs:
        - name: synology
          port: 5001
