---
- name: Configure glusterfs
  hosts: gluster_nodes
  become: true

  tasks:
    - name: Install glusterfs
      ansible.builtin.include_role:
        name: install_glusterfs

- name: Deploy services
  hosts: managers
  become: true

  tasks:
    - name: Deploy traefik
      ansible.builtin.include_role:
        name: traefik
    - name: Deploy homepage
      ansible.builtin.include_role:
        name: homepage
