---
- name: Install system dependencies
  hosts: all
  become: true

  tasks:
    - name: Install essential dependencies
      ansible.builtin.include_role:
        name: install_essential
    - name: Install docker
      ansible.builtin.include_role:
        name: install_docker
