---
- name: Setup swarm cluster
  hosts: all
  become: true

  tasks:
    - name: Create swarm
      ansible.builtin.include_role:
        name: swarm_init
      when: "'managers' in group_names"
    - name: Join swarm
      ansible.builtin.include_role:
        name: swarm_join
      when: "'workers' in group_names"
    - name: Configure swarm
      ansible.builtin.include_role:
        name: swarm_configure
