---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: access-broker-secret-onepassword
  namespace: access-broker
  labels:
    app.kubernetes.io/managed-by: onepassword-operator
    homelab.petebeegle.com/legacy-secret: access-broker-secret
type: Opaque
spec:
  itemPath: "vaults/ydtsmbjna24k5of6ga23boczuu/items/pgsxqs5ue33cqz3p4amyanwnyu"
