---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: authentik-secrets-onepassword
  namespace: authentik
  labels:
    app.kubernetes.io/managed-by: onepassword-operator
    homelab.petebeegle.com/legacy-secret: authentik-secrets
type: Opaque
spec:
  itemPath: "vaults/ydtsmbjna24k5of6ga23boczuu/items/6asz7hfrr3vsyo4ewb6mksc5km"
