---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: tunnel-credentials-onepassword
  namespace: cloudflare
  labels:
    app.kubernetes.io/managed-by: onepassword-operator
    homelab.petebeegle.com/legacy-secret: tunnel-credentials
type: Opaque
spec:
  itemPath: "vaults/ydtsmbjna24k5of6ga23boczuu/items/dhojzrmh37b4rgttqziahgzvla"
