---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: homelab-private-deploy-key-onepassword
  namespace: flux-system
  labels:
    app.kubernetes.io/managed-by: onepassword-operator
    homelab.petebeegle.com/legacy-secret: homelab-private-deploy-key
type: Opaque
spec:
  itemPath: "vaults/ydtsmbjna24k5of6ga23boczuu/items/5sjem2nv4rhsay2k3nr55wtwly"
