---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: foundryvtt-secret-onepassword
  namespace: foundryvtt
  labels:
    app.kubernetes.io/managed-by: onepassword-operator
    homelab.petebeegle.com/legacy-secret: foundryvtt-secret
type: Opaque
spec:
  itemPath: "vaults/ydtsmbjna24k5of6ga23boczuu/items/jjmijft7g63rtunpgwhuxqp5xa"
