---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: grafana-credentials-onepassword
  namespace: grafana
  labels:
    app.kubernetes.io/managed-by: onepassword-operator
    homelab.petebeegle.com/legacy-secret: grafana-credentials
type: Opaque
spec:
  itemPath: "vaults/ydtsmbjna24k5of6ga23boczuu/items/i5jugfy4ozpreex3jwwxouo44m"
