---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: grafana-env-onepassword
  namespace: grafana
  labels:
    app.kubernetes.io/managed-by: onepassword-operator
    homelab.petebeegle.com/legacy-secret: grafana-env
type: Opaque
spec:
  itemPath: "vaults/ydtsmbjna24k5of6ga23boczuu/items/pnqfucrgwhlmbt75eagrm3o2ka"
