---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: immich-postgres-user-onepassword
  namespace: immich
  labels:
    app.kubernetes.io/managed-by: onepassword-operator
    homelab.petebeegle.com/legacy-secret: immich-postgres-user
type: kubernetes.io/basic-auth
spec:
  itemPath: "vaults/ydtsmbjna24k5of6ga23boczuu/items/h3q5utoixi5xglph3l4idzg6xy"
