---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: immich-secrets-onepassword
  namespace: immich
  labels:
    app.kubernetes.io/managed-by: onepassword-operator
    homelab.petebeegle.com/legacy-secret: immich-secrets
type: Opaque
spec:
  itemPath: "vaults/ydtsmbjna24k5of6ga23boczuu/items/qlemiotzsx3iq6gkxjkoi5d7ha"
