---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: jellyfin-secrets-onepassword
  namespace: jellyfin
  labels:
    app.kubernetes.io/managed-by: onepassword-operator
    homelab.petebeegle.com/legacy-secret: jellyfin-secrets
type: Opaque
spec:
  itemPath: "vaults/ydtsmbjna24k5of6ga23boczuu/items/d5j2cavjfkcsdzwhcph7yr6ooy"
