---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: pihole-admin-password-onepassword
  namespace: pihole
  labels:
    app.kubernetes.io/managed-by: onepassword-operator
    homelab.petebeegle.com/legacy-secret: pihole-admin-password
type: Opaque
spec:
  itemPath: "vaults/ydtsmbjna24k5of6ga23boczuu/items/cqqdpqdgsj2kdkvibtluvypm4a"
