---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: renovate-secret-onepassword
  namespace: renovate
  labels:
    app.kubernetes.io/managed-by: onepassword-operator
    homelab.petebeegle.com/legacy-secret: renovate-secret
type: Opaque
spec:
  itemPath: "vaults/ydtsmbjna24k5of6ga23boczuu/items/wwb7bwungpareqqwngybtdi6t4"
