---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: valheim-secret-onepassword
  namespace: valheim
  labels:
    app.kubernetes.io/managed-by: onepassword-operator
    homelab.petebeegle.com/legacy-secret: valheim-secret
type: Opaque
spec:
  itemPath: "vaults/ydtsmbjna24k5of6ga23boczuu/items/rluc4ijztvc2ublf7ik5pgm7xa"
