---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: wireguard-env-onepassword
  namespace: wireguard
  labels:
    app.kubernetes.io/managed-by: onepassword-operator
    homelab.petebeegle.com/legacy-secret: wireguard-env
type: Opaque
spec:
  itemPath: "vaults/ydtsmbjna24k5of6ga23boczuu/items/24ej7c422dfx2j6fi6xl4nvkfy"
