---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc-blue.yaml
  - pvc-green.yaml
  - deployment-blue.yaml
  - deployment-green.yaml
  - service-blue.yaml
  - service-green.yaml
  - httproute-green-preview.yaml
