---
apiVersion: v1
kind: Namespace
metadata:
  name: foundry-bluegreen-fixture
  labels:
    name: foundry-bluegreen-fixture
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
