---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foundry-fixture-green
  namespace: foundry-bluegreen-fixture
  labels:
    app: foundry-bluegreen-fixture
    foundryvtt.petebeegle.com/color: green
spec:
  storageClassName: nfs-csi-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
