---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cloudflare-api-token-onepassword
  namespace: cert-manager
  labels:
    app.kubernetes.io/managed-by: onepassword-operator
    homelab.petebeegle.com/legacy-secret: cloudflare-api-token
type: Opaque
spec:
  itemPath: "vaults/dic43ai4wt5e7vezs454whfrpu/items/ip2lbkjnqx6ukopzpzox2kuwum"
