---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: renovate
  namespace: renovate
spec:
  interval: 1h
  releaseName: renovate
  chart:
    spec:
      chart: renovate
      version: 39.42.4
      sourceRef:
        kind: HelmRepository
        name: renovate
        namespace: flux-system
  values:
    renovate:
      platform: "github"
      endpoint: "https://api.github.com/"
      existingSecret: renovate
      config: |
            {
              "platform": "github",
              "repositories": ["petebeegle/homelab"],
              "baseBranches": ["main"],
            }
    envFrom:
      - secretRef:
          name: renovate-secret
