---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate
  namespace: renovate
spec:
  interval: 1h
  releaseName: renovate
  chart:
    spec:
      chart: renovate
      version: 41.18.1
      sourceRef:
        kind: HelmRepository
        name: renovate
        namespace: flux-system
  values:
    renovate:
      platform: "github"
      endpoint: "https://api.github.com/"
      existingSecret: renovate
      config: |
            {
              "platform": "github",
              "repositories": ["petebeegle/homelab"],
              "baseBranches": ["main"],
            }
    envFrom:
      - secretRef:
          name: renovate-secret
