apiVersion: v1
kind: Secret
metadata:
    name: renovate-secret
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:xDKu4Dm8h/Bvd+RvZkhYlGm9u3/bqSD9ECyYHfp2DAXuJmWTpxEqacUYg3mCqayI1PBI8xmlmiLBA+GVqadu+z9iNf4kQvcVGqrHj1s5pEgIs5cKk7CpqlyyU91f,iv:8DMTlnHtIGbvjfC4EFxZYuLClF820IeFnOT1t98cjOc=,tag:qqDX0IaSDUq92GFQdj2WtA==,type:str]
    GITHUB_COM_TOKEN: ENC[AES256_GCM,data:mWD0Wl6fmfl9eUDsyg61kYL+wwAj5eRyc7C0MQFuJcc5Be3MqzwaMZfYzjeWm4QGt4podaHPjnbjKCN2SMOX8KKYEbSrCT4SZtrSThWkv/tZVTDiGUP9sLlybzAl,iv:v3IO6xWLmqyH3TQTgQwK9k5+KyVzkMe4vAqC1u3B55c=,tag:o56TtG6O4gcBLWgZLTEbWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g4erccmqr8znqmhszfyq425l6dt9thq7vmllrn7z9yjfaug3putqlgs4ry
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUlNhSk16TnYwZ1c4TGRL
            aTE5cXRCRDdYY2FDSTlMSmUrZUlSMFkzVVV3CkpwUlJnWmlkYnlJVVpJSjRBeHN5
            SVozQ0pURnAvNThTb0tselMrWkxacEUKLS0tIFN1c1hsOVRTUWE3bWtLRmdnMXFn
            cWlIWmFhZmhDMGtqV0pqSityYjlLdFEKhXY0653XNJIcSYPl1G0aWbeWYjcoiuhA
            4U7hqVN1h1e8qDl3NoSNIMabSiaVTkPSMvuTL1KQ/JtXHvYjS6QXlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-02T03:34:50Z"
    mac: ENC[AES256_GCM,data:v7b+CT30msBqCJvxDtup+5mWNkq1ZFTtvxep5mSOFAKOVY2g94oJsfP5UU8bSIQlK1BQHItUCUpPzW8bhufbNVFvvoVQdwSFtu0JpHX5f4eVA5nn2aPBoTaxHNrBuaB58+QKxeZvjqjJtoZlwO/yMGibcxSooECy/C8RI0kmfTk=,iv:8ZqIaIPZi/77dwXEKHTBE7VPINqoBXFHAI0sUA3L5Eg=,tag:50R0BnURbsLYmlyz31FrDQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
