---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: monitoring
spec:
  interval: 5m0s
  chart:
    spec:
      chart: kube-state-metrics
      version: 6.3.0
      sourceRef:
        kind: HelmRepository
        name: kube-state-metrics
        namespace: kube-system
  valuesFrom:
    - kind: ConfigMap
      name: ksm-config
