---
- name: Initialize Terraform
  ansible.builtin.command: terraform init
  args: &chdir
    chdir: "{{ lookup('ansible.builtin.env', 'WORKSPACE_FOLDER') }}/terraform"
  environment:
    PM_API_TOKEN_ID: "{{ api_token_id }}"
    PM_API_TOKEN_SECRET: "{{ api_token_secret }}"
- name: Create VM
  ansible.builtin.command: |
    terraform apply -auto-approve \
    -var "ssh_key={{ create_vm_ssh_key }}" \
    -var "template_name={{ template_name }}" \
    -var "number_of_instances={{ number_of_instances }}" \
    -no-color -compact-warnings
  args: *chdir
  environment:
    PM_API_TOKEN_ID: "{{ api_token_id }}"
    PM_API_TOKEN_SECRET: "{{ api_token_secret }}"
    PM_API_URL: "{{ create_vm_proxmox_api_url }}"
- name: Wait for VMs to come online
  ansible.builtin.pause:
    seconds: 20
