---
- name: Check that template does not exist
  ansible.builtin.shell: qm list | grep -q "{{ create_template_id }}"
  register: template_exists
  ignore_errors: true
  changed_when: template_exists.rc == 0
- name: Destroy template # noqa: no-handler
  ansible.builtin.command: qm destroy {{ create_template_id }}
  when: template_exists.changed
- name: Create template
  ansible.builtin.shell: |
    qm create {{ create_template_id }} --name {{ create_template_name }} --memory {{ create_template_memory * 1024 }} \
    --cores {{ create_template_cores }} --net0 virtio,bridge=vmbr0
    qm importdisk {{ create_template_id }} /var/lib/vz/template/iso/focal-server-cloudimg-amd64.img local-lvm
    qm set {{ create_template_id }} --scsihw virtio-scsi-pci --scsi0 local-lvm:vm-{{ create_template_id }}-disk-0
    qm set {{ create_template_id }} --boot c --bootdisk scsi0
    qm set {{ create_template_id }} --ide2 local-lvm:cloudinit
    qm set {{ create_template_id }} --vga serial0 --serial0 socket
    qm template {{ create_template_id }}
