---
- name: Include validation tasks
  ansible.builtin.import_tasks: validate.yml

- name: Create nodes of type {{ add_kubernetes_node_type }}
  ansible.builtin.shell: |
    talosctl apply-config --insecure --nodes {{ item }} --file {{ add_kubernetes_node_config_dir }}/{{ add_kubernetes_node_type }}.yaml
  loop: "{{ add_kubernetes_node_ips }}"
- name: Wait for node to be online and ready to bootstrap
  ansible.builtin.command: talosctl health --wait-timeout 1s
  register: result
  until: "'service \"etcd\" not in expected state \"Running\"' in result.stderr or result.rc == 0"
  retries: 30
  delay: 10
  ignore_errors: true
  failed_when: false
