---
- name: Check that volume exists
  ansible.builtin.stat:
    path: "/glusterfs/bricks/{{ inventory_hostname }}/brick"
  notify:
    - Probe peers
    - Create volume
    - Secure volume
    - Start volume
- name: Create directory
  ansible.builtin.file:
    path: "/glusterfs/bricks/{{ inventory_hostname }}/brick"
    state: directory
    mode: '0644'
