---
- name: Create swarm volume
  ansible.builtin.file:
    path: "/swarm/volumes"
    state: directory
    mode: "0644"
- name: Probe peers
  when: inventory_hostname == groups.gluster_nodes[0]
  ansible.builtin.command: gluster peer probe {{ item }}
  loop: "{{ groups.workers }}"
  changed_when: false
- name: Create volume
  when: not gluster.stat.exists and inventory_hostname == groups.gluster_nodes[0]
  ansible.builtin.command: >
    gluster volume create {{ volume_name }} replica 3 \
    {{ groups.gluster_nodes | map('regex_replace', '$', ':/gluster/data') | join(' ') }} \
    force
  changed_when: false
- name: Secure volume
  when: inventory_hostname == groups.gluster_nodes[0]
  ansible.builtin.command: >
    gluster volume set {{ volume_name }} auth.allow  \
    {{ groups.gluster_nodes | join(',') }}
  changed_when: false
- name: Start volume
  when: not gluster.stat.exists and inventory_hostname == groups.gluster_nodes[0]
  ansible.builtin.command: gluster volume start {{ volume_name }}
  changed_when: false
- name: Mount gluster
  ansible.posix.mount:
    path: /swarm/volumes
    src: localhost:/{{ volume_name }}
    fstype: glusterfs
    state: mounted
