---
- name: Check that volume exists
  ansible.builtin.stat:
    path: "/gluster/data"
  register: gluster
- name: Create gluster directory
  ansible.builtin.file:
    path: /gluster/data
    state: directory
    mode: '0644'
- name: Create XFS filesystem
  community.general.filesystem:
    fstype: xfs
    dev: "/dev/disk/by-id/{{ hdd_device_id }}"
    opts: -i size=512
- name: Mount XFS volume
  ansible.posix.mount:
    path: /gluster/data
    src: "/dev/disk/by-id/{{ hdd_device_id }}"
    fstype: xfs
    state: mounted
