---
- name: Create gluster directory
  ansible.builtin.file:
    path: /glusterfs/bricks/{{ inventory_hostname }}
    state: directory
    mode: '0644'
- name: Create XFS filesystem
  community.general.filesystem:
    fstype: xfs
    dev: "/dev/disk/by-id/{{ hdd_device_id }}"
    opts: -i size=512
- name: Mount XFS volume
  ansible.posix.mount:
    path: /glusterfs/bricks/{{ inventory_hostname }}
    src: "/dev/disk/by-id/{{ hdd_device_id }}"
    fstype: xfs
    state: mounted
