service:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"

rbac:
  extraRules:
    - apiGroups:
        - source.toolkit.fluxcd.io
        - kustomize.toolkit.fluxcd.io
        - helm.toolkit.fluxcd.io
        - notification.toolkit.fluxcd.io
        - image.toolkit.fluxcd.io
      resources:
        - gitrepositories
        - buckets
        - helmrepositories
        - helmcharts
        - ocirepositories
        - kustomizations
        - helmreleases
        - alerts
        - providers
        - receivers
        - imagerepositories
        - imagepolicies
        - imageupdateautomations
      verbs: ["list", "watch", "get"]
    - apiGroups:
        - cert-manager.io
      resources:
        - certificates
      verbs: ["list", "watch", "get"]
    - apiGroups:
        - gateway.networking.k8s.io
      resources:
        - gateways
        - httproutes
        - tlsroutes
      verbs: ["list", "watch", "get"]
customResourceState:
  enabled: true
  config:
    spec:
      resources:
        - groupVersionKind:
            group: kustomize.toolkit.fluxcd.io
            version: v1
            kind: Kustomization
          metricNamePrefix: gotk
          metrics:
            - name: "resource_info"
              help: "The current state of a Flux Kustomization resource."
              each:
                type: Info
                info:
                  labelsFromPath:
                    name: [metadata, name]
              labelsFromPath:
                exported_namespace: [metadata, namespace]
                ready: [status, conditions, "[type=Ready]", status]
                suspended: [spec, suspend]
                revision: [status, lastAppliedRevision]
                source_name: [spec, sourceRef, name]
        - groupVersionKind:
            group: helm.toolkit.fluxcd.io
            version: v2
            kind: HelmRelease
          metricNamePrefix: gotk
          metrics:
            - name: "resource_info"
              help: "The current state of a Flux HelmRelease resource."
              each:
                type: Info
                info:
                  labelsFromPath:
                    name: [metadata, name]
              labelsFromPath:
                exported_namespace: [metadata, namespace]
                ready: [status, conditions, "[type=Ready]", status]
                suspended: [spec, suspend]
                revision: [status, history, "0", chartVersion]
                chart_name: [status, history, "0", chartName]
                chart_app_version: [status, history, "0", appVersion]
                chart_ref_name: [spec, chartRef, name]
                chart_source_name: [spec, chart, spec, sourceRef, name]
        - groupVersionKind:
            group: source.toolkit.fluxcd.io
            version: v1
            kind: GitRepository
          metricNamePrefix: gotk
          metrics:
            - name: "resource_info"
              help: "The current state of a Flux GitRepository resource."
              each:
                type: Info
                info:
                  labelsFromPath:
                    name: [metadata, name]
              labelsFromPath:
                exported_namespace: [metadata, namespace]
                ready: [status, conditions, "[type=Ready]", status]
                suspended: [spec, suspend]
                revision: [status, artifact, revision]
                url: [spec, url]
        - groupVersionKind:
            group: source.toolkit.fluxcd.io
            version: v1
            kind: Bucket
          metricNamePrefix: gotk
          metrics:
            - name: "resource_info"
              help: "The current state of a Flux Bucket resource."
              each:
                type: Info
                info:
                  labelsFromPath:
                    name: [metadata, name]
              labelsFromPath:
                exported_namespace: [metadata, namespace]
                ready: [status, conditions, "[type=Ready]", status]
                suspended: [spec, suspend]
                revision: [status, artifact, revision]
                endpoint: [spec, endpoint]
                bucket_name: [spec, bucketName]
        - groupVersionKind:
            group: source.toolkit.fluxcd.io
            version: v1
            kind: HelmRepository
          metricNamePrefix: gotk
          metrics:
            - name: "resource_info"
              help: "The current state of a Flux HelmRepository resource."
              each:
                type: Info
                info:
                  labelsFromPath:
                    name: [metadata, name]
              labelsFromPath:
                exported_namespace: [metadata, namespace]
                ready: [status, conditions, "[type=Ready]", status]
                suspended: [spec, suspend]
                revision: [status, artifact, revision]
                url: [spec, url]
        - groupVersionKind:
            group: source.toolkit.fluxcd.io
            version: v1
            kind: HelmChart
          metricNamePrefix: gotk
          metrics:
            - name: "resource_info"
              help: "The current state of a Flux HelmChart resource."
              each:
                type: Info
                info:
                  labelsFromPath:
                    name: [metadata, name]
              labelsFromPath:
                exported_namespace: [metadata, namespace]
                ready: [status, conditions, "[type=Ready]", status]
                suspended: [spec, suspend]
                revision: [status, artifact, revision]
                chart_name: [spec, chart]
                chart_version: [spec, version]
        - groupVersionKind:
            group: source.toolkit.fluxcd.io
            version: v1
            kind: OCIRepository
          metricNamePrefix: gotk
          metrics:
            - name: "resource_info"
              help: "The current state of a Flux OCIRepository resource."
              each:
                type: Info
                info:
                  labelsFromPath:
                    name: [metadata, name]
              labelsFromPath:
                exported_namespace: [metadata, namespace]
                ready: [status, conditions, "[type=Ready]", status]
                suspended: [spec, suspend]
                revision: [status, artifact, revision]
                url: [spec, url]
        - groupVersionKind:
            group: notification.toolkit.fluxcd.io
            version: v1beta3
            kind: Alert
          metricNamePrefix: gotk
          metrics:
            - name: "resource_info"
              help: "The current state of a Flux Alert resource."
              each:
                type: Info
                info:
                  labelsFromPath:
                    name: [metadata, name]
              labelsFromPath:
                exported_namespace: [metadata, namespace]
                suspended: [spec, suspend]
        - groupVersionKind:
            group: notification.toolkit.fluxcd.io
            version: v1beta3
            kind: Provider
          metricNamePrefix: gotk
          metrics:
            - name: "resource_info"
              help: "The current state of a Flux Provider resource."
              each:
                type: Info
                info:
                  labelsFromPath:
                    name: [metadata, name]
              labelsFromPath:
                exported_namespace: [metadata, namespace]
                suspended: [spec, suspend]
        - groupVersionKind:
            group: notification.toolkit.fluxcd.io
            version: v1
            kind: Receiver
          metricNamePrefix: gotk
          metrics:
            - name: "resource_info"
              help: "The current state of a Flux Receiver resource."
              each:
                type: Info
                info:
                  labelsFromPath:
                    name: [metadata, name]
              labelsFromPath:
                exported_namespace: [metadata, namespace]
                ready: [status, conditions, "[type=Ready]", status]
                suspended: [spec, suspend]
                webhook_path: [status, webhookPath]
        - groupVersionKind:
            group: image.toolkit.fluxcd.io
            version: v1beta2
            kind: ImageRepository
          metricNamePrefix: gotk
          metrics:
            - name: "resource_info"
              help: "The current state of a Flux ImageRepository resource."
              each:
                type: Info
                info:
                  labelsFromPath:
                    name: [metadata, name]
              labelsFromPath:
                exported_namespace: [metadata, namespace]
                ready: [status, conditions, "[type=Ready]", status]
                suspended: [spec, suspend]
                image: [spec, image]
        - groupVersionKind:
            group: image.toolkit.fluxcd.io
            version: v1beta2
            kind: ImagePolicy
          metricNamePrefix: gotk
          metrics:
            - name: "resource_info"
              help: "The current state of a Flux ImagePolicy resource."
              each:
                type: Info
                info:
                  labelsFromPath:
                    name: [metadata, name]
              labelsFromPath:
                exported_namespace: [metadata, namespace]
                ready: [status, conditions, "[type=Ready]", status]
                suspended: [spec, suspend]
                source_name: [spec, imageRepositoryRef, name]
        - groupVersionKind:
            group: image.toolkit.fluxcd.io
            version: v1beta2
            kind: ImageUpdateAutomation
          metricNamePrefix: gotk
          metrics:
            - name: "resource_info"
              help: "The current state of a Flux ImageUpdateAutomation resource."
              each:
                type: Info
                info:
                  labelsFromPath:
                    name: [metadata, name]
              labelsFromPath:
                exported_namespace: [metadata, namespace]
                ready: [status, conditions, "[type=Ready]", status]
                suspended: [spec, suspend]
                source_name: [spec, sourceRef, name]
        - groupVersionKind:
            group: cert-manager.io
            version: v1
            kind: Certificate
          metricNamePrefix: certmanager
          labelsFromPath:
            name: [metadata, name]
            exported_namespace: [metadata, namespace]
          metrics:
            - name: "certificate_ready_status"
              help: "The Ready condition for a cert-manager Certificate."
              each:
                type: Gauge
                gauge:
                  path: [status, conditions]
                  labelsFromPath:
                    type: [type]
                    reason: [reason]
                  valueFrom: [status]
            - name: "certificate_expiration_timestamp_seconds"
              help: "The notAfter timestamp for a cert-manager Certificate."
              each:
                type: Gauge
                gauge:
                  path: [status, notAfter]
        - groupVersionKind:
            group: gateway.networking.k8s.io
            version: v1
            kind: Gateway
          metricNamePrefix: gatewayapi
          labelsFromPath:
            name: [metadata, name]
            exported_namespace: [metadata, namespace]
          metrics:
            - name: "gateway_status_condition"
              help: "Gateway status conditions."
              each:
                type: Gauge
                gauge:
                  path: [status, conditions]
                  labelsFromPath:
                    type: [type]
                    reason: [reason]
                  valueFrom: [status]
        - groupVersionKind:
            group: gateway.networking.k8s.io
            version: v1
            kind: HTTPRoute
          metricNamePrefix: gatewayapi
          labelsFromPath:
            name: [metadata, name]
            exported_namespace: [metadata, namespace]
          metrics:
            - name: "httproute_parent_accepted"
              help: "HTTPRoute Accepted condition by parent reference."
              each:
                type: Gauge
                gauge:
                  path: [status, parents]
                  labelsFromPath:
                    parent_name: [parentRef, name]
                    parent_namespace: [parentRef, namespace]
                    controller_name: [controllerName]
                  valueFrom: [conditions, "[type=Accepted]", status]
            - name: "httproute_parent_resolved_refs"
              help: "HTTPRoute ResolvedRefs condition by parent reference."
              each:
                type: Gauge
                gauge:
                  path: [status, parents]
                  labelsFromPath:
                    parent_name: [parentRef, name]
                    parent_namespace: [parentRef, namespace]
                    controller_name: [controllerName]
                  valueFrom: [conditions, "[type=ResolvedRefs]", status]
        - groupVersionKind:
            group: gateway.networking.k8s.io
            version: v1alpha2
            kind: TLSRoute
          metricNamePrefix: gatewayapi
          labelsFromPath:
            name: [metadata, name]
            exported_namespace: [metadata, namespace]
          metrics:
            - name: "tlsroute_parent_accepted"
              help: "TLSRoute Accepted condition by parent reference."
              each:
                type: Gauge
                gauge:
                  path: [status, parents]
                  labelsFromPath:
                    parent_name: [parentRef, name]
                    parent_namespace: [parentRef, namespace]
                    controller_name: [controllerName]
                  valueFrom: [conditions, "[type=Accepted]", status]
            - name: "tlsroute_parent_resolved_refs"
              help: "TLSRoute ResolvedRefs condition by parent reference."
              each:
                type: Gauge
                gauge:
                  path: [status, parents]
                  labelsFromPath:
                    parent_name: [parentRef, name]
                    parent_namespace: [parentRef, namespace]
                    controller_name: [controllerName]
                  valueFrom: [conditions, "[type=ResolvedRefs]", status]
