---
apiVersion: v1
kind: Namespace
metadata:
  name: synthetics-${branch_slug}
  labels:
    name: synthetics-${branch_slug}
    app.kubernetes.io/name: synthetic-smoke
    app.kubernetes.io/part-of: branch-environment
    homelab.petebeegle.com/branch-slug: ${branch_slug}
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
